uwblueprint/planet-read

- backend/python/app/rest/auth_routes.py
- frontend/src/components/auth/Login.tsx
- frontend/src/components/auth/ResetPassword.tsx
[Allow users to reset their password](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=4a47edc475b34bb99b25ff1fae2a5507&p=92887fb5e64845e882c4c79a97a18ff6)
* Add reset button to home screen
* Implement basic logic for parsing email string
* Create alerts based on whether the reset email was successfully sent
* Remove authentication requirement that was needed to send reset email
1. Try to reset password from login page with legitimate email form (eg. `test@gmail.com`), random string (eg. `potato`), and real email (eg. `planetread+user@uwblueprint.org`). Should receive email for the latter
2. Login fully and try to reset password, make sure it still works 
* What UI cue are we expecting? This is super, super minimal
* Test coverage suggestions please :))
> Add Reset button to login screen 

- backend/python/app/graphql/queries/user_query.py
- backend/python/app/graphql/schema.py
[Migrate get_users endpoint to GraphQL resolver](https://www.notion.so/uwblueprintexecs/Migrate-get_users-endpoint-to-GraphQL-resolver-460b7d7bb2b0429190163f6f7baf954d)
* add `resolve_user_by_id` and `resolve_user_by_email` to `graphql/queries/user_query.py`
* add calls to `resolve_user_by_id` and `resolve_user_by_email` to `graphql/schema.py`
1. Start up the backend
2. Ensure the database has existing users; otherwise seed database with users:
```
$ planet-read_db_1 psql -U postgres -d planet-read
$ \dt
```
>> if no tables present, change the `erase_db_and_sync` = `False` to `True` in `backend/python/app/models/__init__.py`
```
$ SELECT * FROM users;
```
>> if empty, insert users into the database
```
$ INSERT INTO users (first_name, last_name, auth_id, role) VALUES ('First', 'Last', …
```
> Migrate get_users endpoint to GraphQL resolver

- backend/python/app/graphql/__init__.py
- backend/python/app/graphql/mutations/auth_mutation.py
- backend/python/app/graphql/schema.py
- backend/python/app/rest/auth_routes.py
- frontend/src/components/auth/ResetPassword.tsx
- frontend/src/index.tsx
[Migrate reset_password endpoint to GraphQL](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=4a47edc475b34bb99b25ff1fae2a5507&p=b69224f1963f4ac195c62c71bff4f6da)
* Add mutation for `resetUser(email: String!): ResetUser`
* Migrate call in frontend from REST to GraphQL
* Change `index.tsx` to meet Apollo requirements
1. From backend, try registered email, non-registered emails in GraphQL playground
2. From frontend, try registered email, non-registered email, non-email strings in entry field and check expected message occurs
* Was it necessary to add `services["user"]` in the `__init__.py`?
* Why have other migrations not run into the apollo client issue that required changes in `index.tsx`? ✅ (just hadn't had any other front-end changes yet that were trying to …
> Migrate reset password endpoint to GraphQL

- backend/python/app/graphql/__init__.py
- backend/python/app/graphql/mutations/story_mutation.py
- backend/python/app/graphql/queries/story_query.py
- backend/python/app/graphql/schema.py
- backend/python/app/graphql/service.py
- backend/python/app/graphql/types/story_type.py
- backend/python/app/models/__init__.py
- backend/python/app/models/story_content.py
- backend/python/app/models/story_translation.py
- backend/python/app/models/story_translation_content.py
- backend/python/app/rest/auth_routes.py
- backend/python/app/services/implementations/story_service.py
- backend/python/app/services/interfaces/story_service.py
[Build stories and related models](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=4a47edc475b34bb99b25ff1fae2a5507&p=bc046588cdf24872a208ecf2e1ebfc58)
* add models for stories, story content, and their translations
* see [architecture doc](https://www.notion.so/uwblueprintexecs/Architecture-Brainstorm-44de9f6c559f48f58694164d3aaaf688)
```
mutation {
createStory(storyData: {stage: START, description: "heres my story", youtubeLink: "no!", level: 1, translatedLanguages: []}) {
story {
id
}
}
}
```
```
{
storyById(id:1){
youtubeLink
translatedLanguages
}
}
```
```
{
stories {
youtubeLink
}
}
```
Column index decisions were made based on these queries. Each query uses the indexes to some degree.
```
// Load Homepage
// Show all stories I am translating or reviewing …
```
> Add content related story models and services

- README.md
- backend/python/app/graphql/types/user_type.py
- backend/python/app/models/user.py
- backend/python/app/resources/auth_dto.py
- backend/python/app/resources/user_dto.py
- backend/python/app/services/implementations/user_service.py
[Build User model](https://www.notion.so/uwblueprintexecs/Build-User-model-1030f0330d934282893011ae9249f9bd)
* added profile_pic and resume fields to User model that correspond to an ID in the files table
* added approved_languages field as an object where the key is the language, and the value is the highest level the user is approved for
1. Start up the backend
2. Ensure the database has existing users; otherwise seed database with users:
```
$ planet-read_db_1 psql -U postgres -d planet-read
$ \dt
```
> if no tables present, change the `erase_db_and_sync` = `False` to `True` in `backend/python/app/models/__init__.py`
```
$ SELECT * FROM users;
```
> if empty, insert users into the database
```
$ INSERT INTO users (first_name, last_name, auth_id, role, approved_languages) VALUES …
```
> Build user model

- backend/python/app/graphql/mutations/entity_mutation.py
- backend/python/app/graphql/mutations/user_mutation.py
- backend/python/app/graphql/queries/entity_query.py
- backend/python/app/graphql/queries/user_query.py
- backend/python/app/middlewares/auth.py
- backend/python/app/rest/auth_routes.py
[Add authorization checks to Graphql resolvers](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=4a47edc475b34bb99b25ff1fae2a5507&p=da8927857a284356b83d10053b9ff230)
* Added new middleware method `require_authorization_by_role_gql` that performs the same checks as its non-GraphQL equivalent. Needed to change the arguments and how it accessed headers (request object is in `info.context` rather than just `request`)
* Added the decorator to the appropriate mutations and queries. Justification for adding it on the business logic layer rather than the GraphQL layer (in `schema.py`) based on https://graphql.org/learn/authorization/ 
Also, I added the method into the existing `auth.py` instead of creating a new file because when we eliminate the REST code, the file name …
> Add authorization for user GraphQL endpoints

- backend/python/app/graphql/mutations/user_mutation.py
- backend/python/app/graphql/schema.py
- backend/python/app/graphql/types/user_type.py
- backend/python/app/models/story.py
- backend/python/app/resources/create_user_dto.py
- backend/python/app/resources/user_dto.py
[Migrate update_user endpoint to GraphQL ](https://www.notion.so/uwblueprintexecs/Migrate-update_user-endpoint-to-GraphQL-8ade7c5d1a444caea7bb0a478435dbde)
* Migrated the updateUser mutation with the same format that all the other mutations/queries are being migrated to gql.
* Altered/Updated some DTOs to work with https://github.com/uwblueprint/planet-read/pull/17
1. Build the containers and go to [The GQL Interactive Interface](localhost:5000/graphql)
2. Make sure you have a user in the db, if you need to just go to the homepage and create a new one
3. Craft a mutation under UpdateUser and ensure that your response isn't an error.
4. Profit
* Not sure which DTOs are legacy-isms from REST implementation and removed since there are multiple files named relatively similarly
> Migrate UpdateUser Mutation to GQL

- backend/python/app/graphql/queries/story_query.py
- backend/python/app/graphql/schema.py
- backend/python/app/graphql/types/story_type.py
- backend/python/app/services/implementations/story_service.py
- backend/python/app/services/interfaces/story_service.py
[List StoryTranslations currently being translated or reviewed by User](https://www.notion.so/uwblueprintexecs/List-StoryTranslations-currently-being-translated-or-reviewed-by-User-6d4c73c43a5741979392feb916a475f9)
* added query to return list of StoryTranslations by User based on whether they are a translator (translator=True) or reviewer (translator=False)
1. Seed database with at least 2 users
```
$ docker exec -it <db container id> psql -U postgres -d planet-read
$ INSERT INTO users (first_name, last_name, auth_id, role, approved_languages) VALUES ('First', 'Last', 'insert-firebase-uid', 'Admin', '{"english":3}');
```
2. Seed database with stories/story translation entries
```
$ INSERT INTO stories (title, description, youtube_link, level) VALUES ('my story title', 'story …
```
> List StoryTranslations currently being translated or reviewed by User

- backend/python/app/services/implementations/story_service.py
[Fully load content on storyByID](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=4a47edc475b34bb99b25ff1fae2a5507&p=d2730d8328e948b4be291b19c2aaf126)
* I don't know why this fixes anything I'm sorry
1. Set up your DBs, make sure that you have at least one story
2. Test query:
```
{
storyById(id: 2) {
id
title
contents {
id
storyId
lineIndex
content
}
}
stories {
id
contents {
id
storyId
lineIndex
content
}
}
}
```
3. Make sure `contents` field is not null on either! Either empty array `"contents": []` or something like
```
"contents": [
{
"id": 1,
"storyId": "1",
"lineIndex": 0,
"content": "Line 1"
},
{
"id": 2,
"storyId": "1",
"lineIndex": 1,
"content": "Line 2"
}
]
```
* _why does this work_ 🐋 🐳 🐋 
* About lazy-loading, I chose default behaviour there are …
> Fix bug in content loading for story queries

- backend/python/app/graphql/mutations/story_mutation.py
- backend/python/app/graphql/schema.py
- backend/python/app/graphql/types/story_type.py
- backend/python/app/models/story_translation.py
- backend/python/app/services/implementations/story_service.py
[Assign a User as translator to a story](https://www.notion.so/uwblueprintexecs/Assign-a-User-as-translator-to-a-story-5dbab72c1a53461c96dcf39a7ea24a64)
* Created a new DTO for request & response for creating a story translation
* Creates a new entry for the story translation
* Fetches all the lines associated with the story that's being translated and makes empty lines for those
* Returns the initial story translation entry
1. Build the backend container & go to the [GQL playground](http://localhost:5000/graphql)
2. Ensure you have a story and a user.
3. Query for a random user_id and story_id `stories{user_id}` and `users{user_id}` should do it, fetch any random numbers from those lists
4. Run the following mutation
```
mutation($storyTranslationData: NewStoryTranslationRequestDTO!){ …
```
> Create and Assign User to Story Translation

- frontend/src/components/auth/ResetPassword.tsx
- frontend/src/components/pages/Default.tsx
Dev health thing
* Change from interface to type declaration
1. Start localhost and try reset password when logged in and logged out (with real / not real input)
* More of me being unsure about Typescript conventions. This seems to imply that default props that I'm relying on will be deprecated (https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/default_props/, https://github.com/reactjs/rfcs/pull/107). To be replaced by object default values but we're using functional components everywhere?
* Otherwise, we could declare the type as `string | null` and throw some nullchecks in?
> Change ResetPassword props declaration from type to interface

- backend/python/app/graphql/mutations/auth_mutation.py
- backend/python/app/graphql/schema.py
- frontend/src/components/auth/Logout.tsx
[Migrate logout endpoint to GraphQL](https://www.notion.so/uwblueprintexecs/Migrate-logout-endpoint-to-GraphQL-e9bc15fed00e4dc9b4bb0f8811e08521)
* Copied & pasted code from the rest endpoint for backend 👍
* Refactored frontend to use some hooks
* Good vibes 😎
1. Start the container & go to the web app
2. Login
3. Logout
4. yes
* Nothing much, I think this should be a fairly standard migration, _might_ be subject to the same issues as the [refresh ticket](https://github.com/uwblueprint/planet-read/pull/22) but I doubt it since it seems to work and I don't think that's how auth is implemented.
* Some of the type stuff might be finnicky in the frontend, I've never use Typescript so lmk if I'm violating any best practices
> Logout gql migration

- README.md
- backend/python/app/graphql/mutations/story_mutation.py
- backend/python/app/graphql/schema.py
- backend/python/app/graphql/types/story_type.py
- backend/python/app/services/implementations/story_service.py
- backend/python/app/services/interfaces/story_service.py
[Create updateStoryTranslationContent and updateStoryTranslationContentById mutations](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=4a47edc475b34bb99b25ff1fae2a5507&p=4dd2a92fda8f4d6788c6a55a41e3dc14)
* Added mutation to update story translation content by id: accepts id and new content string
* Added mutation to update story translation content in bulk: accepts list of StoryTranslationContentRequestDTOs (i.e. id and translation_content) and updates all
1. Seed database with values for users, stories, story_contents, story_translations and story_translation_contents (at least 2 for story_translation_contents)
2. Test updating by id:
```
mutation{
updateStoryTranslationContentById(storyTranslationContentData:{
id: 1
translationContent:"updated"
}) {
story {
id …
```
> Create updateStoryTranslationContent mutations

- frontend/src/components/homepage/StoryCard.tsx
- frontend/src/utils/LanguageUtils.ts
- frontend/src/utils/StoryCardUtils.ts
[Add Story Pill](https://www.notion.so/uwblueprintexecs/Add-language-pill-to-all-story-cards-ce7044a46e8944a1891aa613f9b83b0c)
* Add a file in /frontend/src/utils to convert language string to Title Case 
* Remove conditional that storyTranslationId needs to be defined before showing story language pill 
1. Log in as a user and see if story language pill is displayed 
* Ensure that the 4 edge cases are displayed properly (ENGLISH_US, ENGLISH_UK, ENGLISH_INDIA, ASANTE_TWI)
> Add Story Pill to Story Cards 

- seed_db.sh
Bug fix
* Noticed some inconsistency around line indexes. Using mutations/UI for insertion, this should never come up but direct insertion with script commands hides the problem. Think this should solve it
* Made based on https://github.com/uwblueprint/planet-read/pull/39#discussion_r667439779
1. Run script
* Does this fix the issue?
> Fix line index bug and MySQL migration errors in seed_db script

- frontend/src/components/pages/TranslationPage.tsx
- frontend/src/components/translation/Autosave.tsx
- frontend/src/components/translation/EditableCell.tsx
- frontend/src/utils/DebounceUtils.ts
[Use react hooks to avoid per-keystroke auto save](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=4a47edc475b34bb99b25ff1fae2a5507&p=33d890f91c9d4875b59c8a627bf320ff)
* Based on https://www.synthace.com/autosave-with-react-hooks/
* Create debounce function in utils, create Autosave function for the updateStoryTranslationContents call. Note: replaced updateStoryTranslationContentById, as theoretically multiple lines could've been changed within a second. 
* Introduce `changedStoryLines` for state -> to store the changed lines that have to be mutated. Using a Map so that within a second, only 1 call per line changed
1. Make edits on translation page. Refresh/check database to make sure saves are being saved
* Is this a reasonable timeout delay?
* Probably will …
> Refactor saving mechanism into Autosave component

- backend/python/app/services/implementations/story_service.py
- frontend/src/components/pages/TranslationPage.tsx
- frontend/src/components/translation/TranslationProgressBar.css
[Integrate Translation Process Indicator](https://www.notion.so/uwblueprintexecs/integrate-translation-process-indicator-9b9e877c7dce428ab45a9b70a33e0621)
* Set progress bar value on first render based on return value from `storyTranslationById` query
* On user updates, determine if user is adding/removing translation lines and update progress bar accordingly 
* Branch based off of #51 
1. Seed database with stories
2. Navigate to `http://localhost:3000/stories`; select a story and click "translate book"
3. Verify that progress bar originally is at 0%
4. Enter translation: verify that progress bar increments accordingly
5. Delete translation: verify that progress bar decrements accordingly
6. Refresh the page: verify that progress bar value is accurately reflected
* Ensure whitespaces …
> Integrate Translation Process Indicator

- seed_db.sh
Made the seed_db.sh script a bit faster by not calling `docker exec -it planet-read_db_1 mysql -u root -proot -e ` every time we add a new entry. Instead, new entries are added with one `docker exec -it planet-read_db_1 mysql -u root -proot -e ` command. 
There should be a significant speed increase with this new script. 
Run the script and make sure that your databases are being seeded successfully.
> Made the seed_db.sh script more aero

- frontend/src/components/pages/TranslationPage.tsx
[Allow translation undo and redo](https://www.notion.so/uwblueprintexecs/Allow-translation-undo-and-redo-7f36573f90a040748c6cb81f870a7dd1)
* When a user enters a character, takes a snapshot of the current state and pushes it onto a stack.
* Undo -> Pop from undo stack and add current state to redo
* Redo -> Pop from  redo stack and add current state to undo
* Not debounced since figuring out exactly when to snapshot can be tricky esp in conjunction with autosave, this is more MVP for undo/redo.
1. Launch the app and go to the translation page for some story
2. Type some stuff into the translation area, perhaps multiple text areas
3. Press the undo button (not using ctrl + z, that's built into textarea so that would always work), this should undo the last press you've made
4. Try redoing …
> Implemented Undo/Redo Functionality

- frontend/src/APIClients/AuthAPIClient.ts
- frontend/src/APIClients/BaseAPIClient.ts
- frontend/src/APIClients/BaseGQLClient.ts
- frontend/src/APIClients/mutations.ts
- frontend/src/APIClients/queries.ts
- frontend/src/App.tsx
- frontend/src/components/auth/Login.tsx
- frontend/src/components/auth/Logout.tsx
- frontend/src/components/auth/RefreshCredentials.tsx
- frontend/src/components/auth/ResetPassword.tsx
woops, this got larger than it needed to be. I should've split this into two commits but got a little code-happy.
There's two categories of changes:
1. Apollo links to make sure the Authoization header is set
- BaseGQLClient.ts
- App.tsx
2. Modularizing GQL mutations and removing frontend uses of the REST api
- everything else
Adding Apollo links to a custom Apollo client lets us intercept every request made by Apollo (i.e. all our gql requests). Implemented links inject the accessToken into the request header. The accessToken is retrieved from localstorage. If stale, we make a refresh request for a new accessToken.
I modularized GQL mutations as the apollo link needs to use the refresh mutation. Accidentally modularized all auth calls and made the respective components use the …
> fix: send accessToken in request header

- frontend/src/components/pages/TranslationPage.tsx
https://github.com/uwblueprint/planet-read/pull/55#discussion_r680615460
* Comment should explain why this makes sense - replaced all `arrayIndex(lineIndex)` calls with just `lineIndex` since the `arrayIndex(lineIndex) == lineIndex` always
1. Run locally, open up translation page. Did I break anything?
* Does eliminating this method make sense given how design wants the page to be?
> Eliminate arrayIndex method and usages

- backend/python/app/models/comment.py
- backend/python/app/models/story_translation_content.py
- backend/python/app/models/story_translation_content_status.py
- backend/python/app/services/implementations/comment_service.py
- seed_db.sh
[Add status column to story translation content](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=4a47edc475b34bb99b25ff1fae2a5507&p=c0be1a8a0e9c46679f332fd68f98e021)
* create enum for status and add to story_translation_contents
* lazy load story_translation_content on comment
* create_comment sets story_translation_content status to ACTION_REQUIRED
* insert comments in seed_db
1. flip boolean in models/init
2. run `./seed_db.sh` 
3. double check that the database is in a sensible state 
4. test out createcomment mutation ([example query](http://localhost:5000/graphql?variables=null&operationName=createComment&query=mutation%20createComment%7B%0A%20createComment(commentData%3A%7BuserId%3A%201%2C%20content%3A%22hello%22%2C%20storyTranslationContentId%3A%203%7D)%20% …
> Add status column to story_translation_contents

- frontend/src/APIClients/AuthAPIClient.ts
- frontend/src/APIClients/BaseGQLClient.ts
- frontend/src/APIClients/mutations.ts
- frontend/src/APIClients/mutations/AuthMutations.ts
- frontend/src/APIClients/mutations/StoryMutations.ts
- frontend/src/APIClients/queries.ts
- frontend/src/APIClients/queries/StoryQueries.ts
- frontend/src/components/auth/Login.tsx
- frontend/src/components/auth/Logout.tsx
- frontend/src/components/auth/RefreshCredentials.tsx
- frontend/src/components/auth/ResetPassword.tsx
- frontend/src/components/auth/Signup.tsx
- frontend/src/components/homepage/PreviewModal.tsx
- frontend/src/components/homepage/StoryCard.tsx
- frontend/src/components/pages/HomePage.tsx
- frontend/src/components/pages/TranslationPage.tsx
- frontend/src/components/translation/Autosave.tsx
* move all gql request strings to `src/APIClients/mutations.ts` and `src/APIClients/queries.ts`
1. poke around frontend and make sure nothing is broke 💀 
* thoughts on the organization of the files? open to splitting it into 
* `auth_mutations.ts` and `story_queries.ts` (etc)
* eliminating mutation/query distinction and just going with `auth_requests.ts` and `story_requests.ts`
> Modularlize GQL request strings

- .gitignore
- README.md
- backend/python/app/__init__.py
- backend/python/app/config.py
- backend/python/app/conftest.py
- backend/python/requirements.txt
- docker-compose.yml
- utils.sh
(This is the entire description of part 1 and 2.)
[Add pytest](https://www.notion.so/uwblueprintexecs/Add-pytest-78637b82f2d9450eab9ef72dcf011290)
- This is part 1 of 2. Part 2 is available here: https://github.com/uwblueprint/planet-read/pull/69
Test files are found by the following:
- Tests are in a `tests/` directory
- The test file is named `test_<something>.py`
- Each test is defined in a function whose prefix is `test_`:
```python
def test_<describe_the_test>():
pass
```
The available fixtures currently are `app`, `db`, `client`, and `services`. If you pass the name of the fixture as a parameter of the test, it will execute fixture code before running your test and return or yield to you.
```python
def test_<describe_the_test>(app):
result = app.run_something(True)
assert(result) …
```
> Add pytest to backend

- backend/python/app/services/implementations/story_service.py
[Return translation content on storyTranslationsByUser and storyTranslationsAvailableForReview](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=4a47edc475b34bb99b25ff1fae2a5507&p=6a0636cf217e423685acc3909a348d91)
* Use two separate queries, one for the stories based on desired criteria and the other for the story translations with translation content
* Join the the two queries together in a dict and return a list of these dicts
1. Run the `storyTranslationsByUser` and `storyTranslationsAvailableForReview` queries and observe that the `translationContents` field is not null
* Whether this is the best way to get the translation contents as it requires an additional query per row of the main one
> Fix translation content returned as null bug for story translations queries

- frontend/src/components/pages/TranslationPage.tsx
- frontend/src/components/translation/EditableCell.css
- frontend/src/components/translation/EditableCell.tsx
- frontend/src/theme/components/Textarea.ts
- frontend/src/theme/index.ts
[Ticket Name](https://www.notion.so/uwblueprintexecs/Limit-number-of-chars-in-Editable-fb93347b84824cb5adf024371430d478)
* Create new ts file for Textarea to add styling for the editable box 
* Change function that updates editable to not accept new characters after a certain limit 
* Add new message that tells users which lines they are exceeding the limit on  
1. Type in a characters that are double the amount of the original content 
2. Ensure that the text area has red border and there is a message at the top indicating which line is over 
* There is no unintended behaviour when user tries to input more than character limit
> Limit Chars Allowed in Editable 

- frontend/src/components/homepage/StoryCard.tsx
[Limit story card description to 175 characters](https://www.notion.so/uwblueprintexecs/Limit-story-card-description-to-175-characters-b205ce918a7d4d9d8b205d706a91e8e2)
- Limited story card description to 100 characters (instead of 175) to ensure that all descriptions don't exceed the IFrame height
1. Click on My Work or Browse Stories
2. Check each story card
3. Ensure that the descriptions are truncated so that they don't exceed the IFrame height
4. Ensure that the descriptions end in ... if they were truncated
- Character limit can be changed, based on my testing 100 characters ensured that all descriptions don't exceed the IFrame height
> Limit story card description to 100 characters

- frontend/src/components/pages/HomePage.tsx
- frontend/src/theme/components/Button.ts
[add scroll to top button](https://www.notion.so/uwblueprintexecs/add-scroll-to-top-button-d326588e5ec24f9282abbb73b8998f00)
- added a scroll to top button to the stories homepage
1. Rebuild frontend container
2. Login as a user
3. Scroll to bottom of stories page and click scroll to top button
4. Verify that button brings you to top of the page
- `frontend/src/components/pages/HomePage.tsx`
- `frontend/src/theme/components/Button.ts`
> Add Scroll to Top Button

- backend/python/app/services/implementations/story_service.py
[](url)
[return stories of specific level from storiesAvailableForTranslation](https://www.notion.so/uwblueprintexecs/return-stories-of-specific-level-from-storiesAvailableForTranslation-79bf358ea4f9483c93460ccfe38cd7f0)
- Converted all of the lines filtering using `Story.level <= level` to `Story.level == level`
1. Click on "My Work" or "Browse Stories" under either Translator or Reviewer roles
2. Click through different access levels
3. Verify that only stories equal to the selected access level are displayed
- Some of the lines use `Story.level == level if level else True` to handle the case that level is None, not sure if this should be added for all lines that check `Story.level == level` (for the sake of consistency)
> Return stories equal to provided level from storiesAvailableForTranslation query

- backend/python/app/graphql/types/story_type.py
- backend/python/app/models/story_translation.py
- backend/python/migrations/versions/3f6fff20884c_initial_migration.py
[Remove START stage from story_translation](https://www.notion.so/uwblueprintexecs/Remove-START-stage-from-story_translation-50c198ff022e498bbca0b9be4ea82b47)
- Removed START stage from story translation by deleting all START translation stage enums from project files (3 instances found)
1. Translation page should be working exactly as it was before
2. Check that starting a translation works:
a. Set role required to translator
b. Click my work
c. Note the books currently being translated
d. Click browse stories
e. Click translate book for any book that is not currently being translated
f.  Click my work
g. Check that the book is now being translated
- All 3 instances of the START translation stage enum were removed, and it doesn't seem to be used anywhere else. If possible, please double …
> Remove START stage from story_translation

- backend/python/app/middlewares/auth.py
- backend/python/app/services/implementations/auth_service.py
- backend/python/app/services/interfaces/auth_service.py
- added `get_user_id_from_request `utility to middlewares.auth.py
- added `is_reviewer `to auth service
`get_user_id_from_request `
You're gunna have to trust me on this one, LOL. Here's how to use it in a service:
opening the homepage and browsing stories as translator would cause the user id to be printed. 
is_reviewer 
This is essentially the same code as is_translator. To test, go to translation page and type some stuff. The translation should be successfully updated, ie refreshing the page will keep the changes made.
- clarity
> Add is_reviewer and get_user_id_from_request

- frontend/src/components/pages/ReviewPage.tsx
- frontend/src/components/pages/TranslationPage.tsx
- frontend/src/components/review/CommentsPanel.tsx
- frontend/src/components/review/WIPComment.tsx
- frontend/src/components/translation/TranslationTable.tsx
[Make per-line comment button functional](https://www.notion.so/uwblueprintexecs/Make-per-line-comment-button-functional-9cb870ccaae44e8eba0f899370ea288f)
- added flow for adding comments, with the exception of displaying them 
- added state variables at the TranslationPage level, to pass them between TranslationTable and CommentsPanel
1. Open the app frontend and navigate to a story 
2. Click the comment button in the commentspanel (top right) -> comment buttons should appear in each row 
3. Pick a line and click the comment button -> WIPComment component should appear in pannel
4. Add a comment in the WIPComment component  
- Flow as expected?
- Better way to store state?
> Make per-line comment button functional

- backend/python/app/graphql/mutations/story_mutation.py
- backend/python/app/graphql/schema.py
- backend/python/app/graphql/types/story_type.py
- backend/python/app/middlewares/auth.py
- backend/python/app/services/implementations/story_service.py
- backend/python/app/services/interfaces/story_service.py
[Create updateStoryTranslationStage](https://www.notion.so/uwblueprintexecs/Create-updateStoryTranslationStage-c6bc9384ff07447e84f5a1f24eec627c)
- created a method in StoryService called `update_story_translation_stage` that updates the story translation's stage to the new stage if the user is authorized to perform the operation
- the mutation resolver pretty much just calls the method
- currently we only care about updating the stage to `TRANSLATE` or `REVIEW`, updating to `PUBLISH` will be handled separately in a different mutation
1. Go to `localhost:5000/graphql`
2. To test the mutation you will need the `id` of a story_translation as well as its `translator_id`, for testing I used `id: 12` and `translator_id: 3`, which corresponds to user "Kevin Debryune"
3. Run the following …
> Create updateStoryTranslationStage mutation

- frontend/src/components/pages/TranslationPage.tsx
- frontend/src/components/translation/UndoRedo.tsx
- frontend/src/utils/DeepCopyUtils.ts
[Debounce translation undo redo](https://www.notion.so/uwblueprintexecs/Debounce-translation-undo-redo-12b5178abf5e4120ab34f23e666d190c)
* The name is a misnomer, since it's not quite debounced, since users might want to have more granularity in undos than what the debounced approach would offer. 
* Instead, the state is stored every second and users can iterate over those in the undo, otherwise all functionality is essentially the same as https://github.com/uwblueprint/planet-read/pull/55.
1. Open a story
2. Type some things
3. Undo some things
4. Redo some things
5. Try undoing all your changes and redoing all your changes
6. Try undoing after no changes
7. Give yourself a pat on the back for being a cool person :)
* Not sure about how the timings feel, whether or not the exact amount …
> Implemented debounced undo

- frontend/src/APIClients/queries/StoryQueries.ts
- frontend/src/components/pages/ReviewPage.tsx
- frontend/src/components/pages/TranslationPage.tsx
- frontend/src/components/review/CommentsPanel.tsx
- frontend/src/components/translation/TranslationTable.tsx
- frontend/src/utils/Copy.ts
[Disable editing on translation platform if stage is REVIEW](https://www.notion.so/uwblueprintexecs/Disable-editing-on-translation-platform-if-stage-is-REVIEW-2b719a09478146e29d2c43d2cfa64c43)
- disabled commenting, editing, and submitting when story translation is NOT in TRANSLATE state (instead of when story is in review)
- added tooltips 
1. Set a story to be in REVIEW through mysql CLI 
2. "Send for review" button should now show "In review", table should not be editable, commenting should be disabled 
3. Tooltips should show up on these three areas 
4. Tooltips should NOT show up when in translate, buttons, commenting, and editing should work properly 
- I personally found that the tooltips on the text cells (in the table) were felt a bit unnecessary (and even distracting) --> would …
> Disable editing on translation platform if stage is REVIEW

- backend/python/app/graphql/mutations/story_mutation.py
- backend/python/app/graphql/schema.py
- backend/python/app/graphql/types/story_type.py
- backend/python/app/services/implementations/story_service.py
- backend/python/app/services/interfaces/story_service.py
- frontend/src/APIClients/mutations/StoryMutations.ts
- frontend/src/components/pages/ReviewPage.tsx
- frontend/src/components/pages/TranslationPage.tsx
- frontend/src/components/review/StatusBadge.tsx
- frontend/src/components/translation/TranslationTable.tsx
[Add Status Pill](https://www.notion.so/uwblueprintexecs/Add-status-pill-to-lines-and-allow-reviewer-to-change-status-e672959f12f642dfbcd13d0661b613ad)
- Add GQL mutation to change the status of a line on the review page 
- Add menu to status pill on frontend to allow user to select new status 
- Update the review progress bar from the frontend as well 
- Nothing is broken, no weird edge cases
> Add status pill for single line

- frontend/src/components/homepage/PreviewModal.tsx
[open View anibook link in new tab](https://www.notion.so/uwblueprintexecs/open-View-anibook-link-in-new-tab-ae8c1ec3f25240059b9341d003680283)
- Quick one line (one prop?) change to pass in `isExternal=true` to [Chakra UI Link](https://chakra-ui.com/docs/navigation/link#external-link) to have View anibook link open in a new tab
1. Pull latest changes and login to any user
2. Click on "Preview Book" button, and click "→ Watch the English AniBook"; verify that the youtube link opens in a new tab
- `frontend\src\components\homepage\PreviewModal.tsx`
- since Chakra UI Links makes it really easy to open in a new tab, I don't think a utility is necessary; let me know if you think creating a wrapper around the Chakra UI Link component to ensure all links have an `isExternal=true` prop set by …
> Open View anibook link in new tab

- frontend/src/components/homepage/StoryCard.tsx
["View translation" button should open to /review for homepage reviewer story card](https://www.notion.so/uwblueprintexecs/View-translation-button-should-open-to-review-for-homepage-reviewer-story-card-ed428178d71a4c8a83be6f5ce7bd183b)
- Check if user is reviewer before routing to `/translation` or `/review` 
1. Log in as a user and navigate to the "My Work" tab
* Make sure the user is translating and reviewing at least one story (Dwight D Eisenhower is already translating and reviewing stories based on the seed script)
2. Click on the "View Translation" button for a story the user is translating; this should open up the translation platform
3. Click on the "View Translation" button for a story the user is reviewing; this should open up the review platform
- Checking that change didn't …
> Open /review for reviewer story card "View Translation" button

- frontend/src/APIClients/mutations/StoryMutations.ts
- frontend/src/components/pages/TranslationPage.tsx
- frontend/src/components/translation/SendForReviewModal.tsx
[Implement Send For Review Flow](https://www.notion.so/uwblueprintexecs/Implement-Send-To-Translator-flow-b235b41a9e4b43c892b17af495fdbb52)
- Added SendForReviewModal that opens when a user clicks Send for Review
- When modal is confirmed, story is moved to review stage and page refreshes 
1. Click View Translation for a story under My Work
2. Click Send for Review (modal should appear)
3. Test closing and reopening the modal
4. Click I'm Sure, Send for Review
5. Check that page refreshes
6. Check that story stage is Review in story_translations table
- Does modal look good?
- Do buttons work as intended?
- Is story stage changed to review?
> Implement Send For Review Flow

- frontend/.eslintrc.js
- frontend/src/APIClients/mutations/AuthMutations.ts
- frontend/src/components/homepage/Filter.tsx
- frontend/src/components/pages/HomePage.tsx
- frontend/src/contexts/AuthContext.ts
- frontend/src/theme/components/Filter.ts
- frontend/tsconfig.json
[Reflect filter based on two approved languages pipelines](https://www.notion.so/uwblueprintexecs/reflect-filter-based-on-two-approved-languages-pipelines-f0b7b4a5aa634f8ea515e47701cbf003)
- updated mutation and auth user type to fetch approvedLanguagesReview
- minor restyling for Filter component to use margins instead of `justifyContent: space-between`
- display "Role required" box only if `approvedLanguagesReview` object is not empty
- display access level options based on approved level, **previously all levels from 1->4 were displayed**
1. Log in using `planetread+carlsagan@uwblueprint.org`, the sidebar shouldn't display the "Role required" section (since Carl Sagan is only approved as a translator)
2. Clear localStorage and log in as `planetread+miroslavklose@uwblueprint.org`, the …
> Reflect filter based on two approved languages pipelines

- frontend/src/components/pages/TranslationPage.tsx
- frontend/src/components/translation/TranslationTable.tsx
- frontend/src/theme/components/Text.ts
[Create save status component](https://www.notion.so/uwblueprintexecs/Create-Save-status-component-a9c1daa9d59548b3aff85cbe109e6902)
- Added `Progress Saved`/`Progress Saving...` text to indicate when translator edits are saved
1. Login as a user who is translating a story
2. Go to the translation platform 
3. Enter some text and verify that the progress status changes from `Progress Saved` to `Progress Saving...`
4. Wait until the text says `Progress Saved` again
5. Refresh the page and verify that changes persist
- `frontend/src/components/translation/TranslationTable.tsx`
- still waiting on thumbs up from #planetread-design
> Create save status component

- frontend/src/components/translation/TranslationTable.tsx
Made a quick bug fix to prevent 'Progress Saving...' indicator from appearing on the review page.
> Fix bug where 'Progress Saving' indicator appears on Review Page

- backend/python/tools/insert_test_data.py
- Add 10 empty lines to story translation contents instead of 9 empty lines in seed script
1. Run (inside of backend container): `python -m tools.insert_test_data erase` and `python -m tools.insert_test_data`
2. Verify that story translation platform works properly (this should fix the bug where the last line in the translation table doesn't render properly)
-
> Fix seed script empty translation bug

- frontend/src/components/review/StatusBadge.tsx
Found a bug on the status pill where the confirmation modal shows up if the reviewer wants to approve a line that is already approved. This is not intended behaviour as we only want the modal to show up when the reviewer wants to approve the last unapproved line. 
(Video for context) 
https://drive.google.com/file/d/13UxguDck9zsVMCuKmKwtqWJ-Ka6l_XcC/view?usp=sharing
> Fix bug where confirmation modal pops up unintentionally

- frontend/src/components/admin/ManageReviewers.tsx
- frontend/src/components/admin/ManageStoryTranslations.tsx
- frontend/src/components/admin/ManageTranslators.tsx
- frontend/src/components/navigation/Header.tsx
- frontend/src/components/pages/AdminPage.tsx
- frontend/src/theme/components/Button.ts
[Implement admin Header](https://www.notion.so/uwblueprintexecs/Implement-admin-Header-cf4f924ec0e04a26ac594a8cfc64dac4)
- /admin now has header options that switch what's displayed in the admin page
- the header has undergone some css changes to support this. The header appears thinner on the homepage and translation/review pages now
1. log in. observe the homepage header looks ok
2. view translation. observe the header looks ok
3. go to /admin. observe the header looks ok
4. clicking the different tabs should switch the component in the body of the admin page
- does it work
> Implement admin Header

- frontend/src/APIClients/queries/UserQueries.ts
- frontend/src/components/admin/ManageReviewers.tsx
- frontend/src/components/admin/ManageTranslators.tsx
- frontend/src/components/admin/UsersTable.tsx
[Create Translators/Reviewers Table](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=4412841e4ef34210968a3aec024b7b07)
- used current `users` query for now
- added `UserTable`, flexible with `Translators` and `Reviewers` screens
**note** that
- name column does not sort
- delete user button does nothing
- there is no pagination
Tickets in our task board will be updated accordingly based on what is left over to complete
1. login and go to /admin
2. view manage translators and manage stories
3. admire the lit af tables 🔥 
4. hover and click a user's name. observe that it takes you to their user page
5. hover and click a user's email. observe that it opens your email client to the user's email
6. observe that the APPROVED LANGUAGES …
> Create Translators/Reviewers Table

- frontend/src/components/homepage/PreviewModal.tsx
- frontend/src/components/homepage/StoryCard.tsx
- frontend/src/theme/components/Badge.ts
- frontend/src/theme/components/Text.ts
- frontend/src/utils/StatusUtils.ts
[Style Preview Modal](https://www.notion.so/uwblueprintexecs/Style-preview-modal-according-to-hi-fi-designs-cc078c98da544fc4a40fab0127bdaae5)
- Style the preview modal according to design document 
- Add new option to preview story translation by displaying both the original story and the translated content 
1. Open the preview modal on a story from the 'Browse Stories' tab and ensure styling is consistent 
2. Open the preview modal on a story translation and ensure that the styling is consistent 
- Styling matches design document
> Style preview modal according to hi-fi designs

- frontend/src/components/admin/UsersTable.tsx
- frontend/src/components/homepage/StoryCard.tsx
- frontend/src/theme/components/Badge.ts
[Display correct language badge colors on UserTable](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=92be83d79e2d4a49900ca36c358c0dde)
(did not make separate ticket for StoryCard)
- use variants `language` and `stage`
- make and use variant `role`
- use `getLevelVariant`
1. login
2. look at story cards. noice
3. go to /admin. look at manage translators and manage reviewers. noice
- does it look pwetty uwu
> Use correct badge styles

- backend/python/app/graphql/types/story_type.py
- backend/python/app/services/implementations/story_service.py
[Return translator name and reviewer name in getStoryTranslations](https://www.notion.so/uwblueprintexecs/Return-translator-name-and-reviewer-name-in-getStoryTranslations-70e77a15524f4f8cbf11c1991450e8d7)
- Updated `getStoryTranslations` to return translator/reviewer full name
2. Test that translator and reviewer full names are returned in getStoryTranslations [query](http://localhost:5000/graphql?query=%7B%0A%20%20storyTranslations%20(storyTitle%3A%20%22and%22)%20%7B%0A%20%20%20%20title%0A%20%20%20%20id%0A%20%20%20%20description%0A%20%20%20%20level%0A%20%20%20%20language%0A%20%20%20%20stage%0A%20%20%20%20translatorId%0A%20%20%20%20reviewerId%0A%20%20%20%20translator%0A%20%20%20%20reviewer%0A%20%20%7D%0A%7D%0A)
3. Play around with the filters to ensure joining with users …
> Return translator name and reviewer name in getStoryTranslations

- frontend/src/APIClients/queries/StoryQueries.ts
- frontend/src/App.tsx
- frontend/src/components/admin/ManageStoryTranslations.tsx
- frontend/src/components/admin/StoryTranslationsTable.tsx
- frontend/src/components/admin/UsersTable.tsx
- frontend/src/components/pages/ManageStoryTranslationPage.tsx
- frontend/src/components/pages/ManageStoryTranslationsPage.tsx
- frontend/src/utils/LanguageUtils.ts
- frontend/src/utils/Utils.ts
[Create Story Translations Table](https://www.notion.so/uwblueprintexecs/Create-Story-Tranlsations-Table-007c74b708fc436ab6dc4f85dc0a1e2b)
- Create story translations table
- Added new route `/story/:storyId/:storyTranslationId`
1. Login as an admin and navigate to `/admin`
2. Check that the story translations table renders properly
3. Check that clicking on the story title brings you to `/story/:storyId/:storyTranslationId`
4. Check that clicking on the translator's name/reviewer's name brings you to `/user/:userId`
- does the table look okay?
- does the route `/story/:storyId/:storyTranslationId` make sense? (technically story-translation not story)
- should i build out the `buildStoriesQuery` in this PR?
> Create Story Translations Table

- backend/python/app/services/implementations/user_service.py
[:3](https://www.notion.so/uwblueprintexecs/Return-getUsers-with-level-param-only-aee4ad72b23947c182b9a6f951d1bcea)
- in get_users() in `\backend\python\app\services\implementations\user_service.py`, filter the list of `user_dtos` by level before returning 
1. Go to admin page and Manage Reviewers / Translators 
2. Only select the level filter parameter 
3. The resulting list of users should be all users that are approved for a language in that level 
- Small PR, just make sure nothing breaks 
[hi](https://www.economist.com/leaders/2020/10/29/why-it-has-to-be-biden)
> return with level param only

- backend/python/app/graphql/schema.py
- backend/python/app/graphql/types/story_type.py
- backend/python/app/services/implementations/story_service.py
- backend/python/app/services/interfaces/story_service.py
[Paginate getStoryTranslations](https://www.notion.so/uwblueprintexecs/Paginate-getStoryTranslations-d86ce7ed0c904d469226b785af549c98)
- Used graphene relay to add pagination by creating a Connection and modifying the `story_translations` query in `schema.py`
- Created a new object type called `StoryTranslationNode` that represents the returned object for a story translation
1. Using the Altair client, using the following mutation to log in, then copy the access token and set the authorization header:
```
mutation Login {
login (email:"planetread+angelamerkel@uwblueprint.org", password:".") {
accessToken
refreshToken
id
}
}
```
2. Fetch all story translations using 
```
query StoryTranslations {
storyTranslations(first: 13) {
edges {
cursor
node {
storyTranslationId
title
language
stage
} …
```
> Implement pagination for getStoryTranslations query

- frontend/src/APIClients/queries/StoryQueries.ts
- frontend/src/components/admin/ManageStoryTranslations.tsx
- frontend/src/components/admin/StoryTranslationsTable.tsx
- Fixed the shape of the `storyTranslations` query and how it's parsed in `ManageStoryTranslations.tsx`
1. Log into the admin account: `planetread+angelamerkel@uwblueprint.org`
2. Go to `/admin` and verify that the story translations appear in the table
- Verifying that the story translations are fetched and show up
> Fix getStoryTranslation query on frontend

- backend/python/app/services/implementations/story_service.py
- frontend/src/APIClients/queries/StoryQueries.ts
- frontend/src/components/admin/ManageStoryTranslations.tsx
- frontend/src/components/admin/ManageUsers.tsx
- frontend/src/components/admin/TableFilter.tsx
- frontend/src/constants/Stage.ts
- frontend/src/utils/Copy.ts
- frontend/src/utils/StageUtils.ts
[Create Story Translations filters](https://www.notion.so/uwblueprintexecs/Create-Story-Translations-filters-263b6b271ede47bda3b1fc7bbb506b9e)
- Generalize the filter component so that it can be used for both the User table and Story Translation table 
- Modify `buildStoriesQuery` in `frontend\src\APIClients\queries\StoryQueries.ts` to take in filter parameters 
1. Go to the Manage  Story Translations section of the admin page and make sure filtered queries return as expected 
2. Go to the Manage Translators and Manage Reviewers page as well to make sure nothing has broken after the filter component has been generalized 
- None of the filters are broken 
- Try some different combinations of filters
> Generalize filter component and create story translations filter 

- frontend/src/APIClients/mutations/CommentMutations.ts
- frontend/src/APIClients/queries/CommentQueries.ts
- frontend/src/components/review/CommentsPanel.tsx
- frontend/src/components/review/ExistingComment.tsx
- frontend/src/theme/components/Button.ts
[Create existing comment component](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=4a47edc475b34bb99b25ff1fae2a5507&p=db62b18f0f9f4422a833567c45883520)
- Created gql mutation for updating user
- Created Existing comment component
1. Confirm pressing reply opens a WIPComment component (only when the Comments button is toggled) and pressing cancel on the WIPComment component closes it
2. Confirm pressing respond updates the resolved value for the comment in the db and updates the value of the comments state var
- That the functionality is as desired
> Create Existing comment component

- frontend/src/APIClients/mutations/UserMutations.ts
- frontend/src/components/admin/UsersTable.tsx
- frontend/src/utils/Copy.ts
[Delete users on UserTable](https://www.notion.so/uwblueprintexecs/Delete-users-on-UserTable-50448562dd97467d96bd11b2ce677b9a)
- make soft delete call in `UsersTable.tsx`
- basically the same changes as: https://github.com/uwblueprint/planet-read/pull/148
1. Login using `planetread+angelamerkel@uwblueprint.org`
2. Go to `/admin` and click on "Manage Translators" or "Manage Reviewers"
3. Try to delete any user
4. Verify that the user doesn't appear in the table anymore 
- Does the deletion work?
- Currently the behaviour for both `StoryTranslationsTable` and `UsersTable` is to reload the window after deletion, but the page will get reset to the `StoryTranslationsTable` page - is this something we want to handle or should we leave it as is?
> Delete users on UserTable

- frontend/src/components/review/CommentsPanel.tsx
- frontend/src/components/review/ExistingComment.tsx
- frontend/src/components/review/WIPComment.tsx
[Make the Comments Panel scrollable](https://www.notion.so/uwblueprintexecs/Dev-Tasks-ebe211395a364645a115234ddf1c887f?p=e2a6e60e8c454556aa5c5cc3fe807ba0)
- Minor css changes to make the comments panel vertically scrollable
1. View comments panel on translation page
- If the user presses the reply button, the indented WIPComment makes the panel horizontally scrollable as well since the comment is slightly outside the margins. Should I increase the width of the panel to account for this? (Note: I already increased the width so increasing the width further might look a bit strange)
vs
> Make CommentsPanel scrollable

- frontend/src/APIClients/queries/StoryQueries.ts
- frontend/src/components/homepage/StoryCard.tsx
- frontend/src/components/pages/ManageStoryTranslationPage.tsx
- frontend/src/utils/LanguageUtils.ts
- frontend/src/utils/StageUtils.ts
- frontend/src/utils/Utils.ts
[Ticket Name](https://www.notion.so/uwblueprintexecs/Implement-dumb-admin-story-translation-page-731159c382c5406ea3ea3fb619465d16)
- implement side bar 
- backend needs to be modified to return the translator/reviewer names and the total number of lines
- implemented form 
- making a dumb non functioning form for now
- implemented bottom footer  
- buttons are non functioning
- using default nav for now   
tldr, only functioning thing is the delete button
1. login as angela merkel
2. go to http://localhost:3000/story/1/1
3. modify the last number in the url to see different story translations
4. attempt to delete translation 
5. observe redirect to homepage
6. attempt to open the last url. observe the 404
> Implement base Story Translation page

- frontend/src/components/review/CommentsPanel.tsx
- frontend/src/components/review/ExistingComment.tsx
[Indent existing comment replies](https://www.notion.so/uwblueprintexecs/Indent-existing-comment-replies-24b764f717434bc79347a4bc6194e88c)
- Indent if the comment index is not 0 and add copy "Replies to" 
1. Login as Carl Sagan
2. Go to http://localhost:3000/translation/6/13 
3. See that the comments are indented 
- Does it work and look right?
> Indent existing comment replies

- backend/python/app/graphql/types/comment_type.py
- backend/python/app/services/implementations/comment_service.py
- frontend/src/APIClients/mutations/CommentMutations.ts
- frontend/src/APIClients/queries/CommentQueries.ts
- frontend/src/components/pages/ReviewPage.tsx
- frontend/src/components/pages/TranslationPage.tsx
- frontend/src/components/review/CommentsPanel.tsx
- frontend/src/components/review/ExistingComment.tsx
- frontend/src/components/review/WIPComment.tsx
- frontend/src/components/translation/TranslationTable.tsx
[Display the correct line number on existing comments](https://www.notion.so/uwblueprintexecs/Display-the-correct-line-number-on-existing-comments-4a8316cf49bd4c6fa8fa488e457f2991)
- Fetch the line number from the StoryTranslationContent in backend, 
- *I think there was some confusion around the naming with regards to comment index which led to the bugs*, renamed them to hopefully be clearer (?):
- `commentIndex` and `WIPCommentIndex` refer to the comment number for a specific thread (the first comment in any thread will have commentIndex=0, the first reply to that comment will be commentIndex=1)
- `lineIndex` is the specific StoryTranslationContent line number that the comment refers to 
1. Log in as carl sagan and go to http://localhost:3000/translation/6/13 
2. Check that the comment …
> Display the correct line number on existing comments

- frontend/package.json
- frontend/src/App.tsx
https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=bc5ded5818494010a5694eea80fbe9be
- upped the chakra ui version. this fixed the issue for philips' windows system dark mode
- added code forcing charkaui to toggle to light mode. this fixed the issue for my windows system dark mode
1. open page
2. make sure it's light mode
3. toggle your system default app mode to dark
4. verify that the page is still in light mode
5. try turning your entire system to dark
6. verify that the page is still in light mode
- is it l i g h t 💡
> Prevent Dark Mode in chakraui

- backend/python/app/conftest.py
- backend/python/app/tests/graphql/mutations/test_story_mutation.py
- backend/python/app/tests/graphql/queries/test_story_query.py
- backend/python/app/tests/services/test_story_service.py
- backend/python/tools/migrate_and_pytest.sh
- docker-compose.testing.yml
[Apply DB migrations to test_db in before running pytest](https://www.notion.so/uwblueprintexecs/Apply-DB-migrations-to-test_db-in-before-running-pytest-9825824895354fdebd3762184486f219)
- Change env variables for `DB_HOST` and `TEST_DB_HOST` in circleCI 
- Change command for test command in `docker-compose.testing.yml` 
- Call migrations before pytest 
1. Make sure there is a green check mark  ✔️ 
- Changes make sense
> call migration before running pytest for circleci

- frontend/src/APIClients/mutations/CommentMutations.ts
- frontend/src/APIClients/queries/CommentQueries.ts
- frontend/src/components/review/ExistingComment.tsx
- frontend/src/components/review/WIPComment.tsx
[Correct comment creation behaviour for replies](https://www.notion.so/uwblueprintexecs/Correct-comment-creation-behaviour-for-replies-84eae6e9151d4051b7ec8ee5416c93d4)
- storyTranslationContentId wasn't getting passed in correctly 
- commenting state was also weird (right now the blue comment flow should be separate from the reply flow)
1. Go to http://localhost:3000/translation/6/13 as Carl Sagan
2. Without clicking on the big blue comment button, click on Reply for any of the existing comments and try to comment
3. Now click on the big blue comment button
4. Click on line numbers, check that commenting works 
Note: the ordering of comments is strange, probably needs to be addressed in future PR. 
- Does the commenting work as expected?
> Fix comment creation behaviour for replies

- .circleci/config.yml
- backend/python/app/conftest.py
- backend/python/app/tests/graphql/mutations/test_story_mutation.py
- backend/python/app/tests/graphql/queries/test_story_query.py
- backend/python/app/tests/services/test_story_service.py
- backend/python/tools/insert_test_data.py
[move clearing tables from unit tests to conftest.py db fixture](https://www.notion.so/uwblueprintexecs/move-clearing-tables-from-unit-tests-to-conftest-py-db-fixture-de088e2008144ccb84dfc75b7d304ab8)
- move delete steps to db teardown in `conftest.py`
1. Verify CircleCI tests pass!
- `conftest.py`
> Move clearing tables to fixture teardown

- backend/python/app/services/implementations/comment_service.py
- frontend/src/components/review/WIPComment.tsx
- frontend/src/utils/Utils.ts
[Correct Comment ordering](https://www.notion.so/uwblueprintexecs/Correct-Comment-ordering-6f8dd1161e334fbe9bbd6d821e098c95)
- Sort comments when retrieving from DB 
- Insert new comments sorted on frontend 
1. Go to http://localhost:3000/translation/6/13 as carl sagan 
2. Add comments and check that they show up correctly
3. Try inserting at the beginning, replying, at the end
4. Might need to delete the existing comments on Line 1 to check beginning (`delete from comments where story_translation_content_id = 51;`)
> Sort comments by line and comment index

- backend/python/app/tests/helpers/db_helpers.py
- backend/python/app/tests/helpers/story_helpers.py
- backend/python/app/tests/services/test_story_service.py
https://www.notion.so/uwblueprintexecs/Write-get_story-get_stories-create_story-tests-in-test_story_service-py-6dd88eabe56b4579a1766da332d607ea
- write unit test
- make dummy StoryResponseDTO class in story_helper
1. observe that circle ci test pass 😎 
- is it readable?
- what do you think about the dummy StoryResponseDTO class living in story_helper?
> Write get_story and create_story unit tests

- frontend/src/components/admin/EmptyTable.tsx
- frontend/src/components/admin/ManageStoryTranslations.tsx
- frontend/src/components/admin/ManageUsers.tsx
- frontend/src/components/admin/StoryTranslationsTable.tsx
- frontend/src/components/admin/UsersTable.tsx
- frontend/src/theme/components/Heading.ts
- frontend/src/utils/hooks/usePagination.tsx
[Add empty columns table response to UsersTable and StoryTranslationsTable](https://www.notion.so/uwblueprintexecs/Add-empty-columns-table-response-to-UsersTable-and-StoryTranslationsTable-eed664e5b725466da3611c54e0a564bb)
- Added a new empty table respone component, accepts array of filters to be set to null
1. Go to http://localhost:3000/admin as angela merkel
2. Add some filters until there aren't any rows
3. See that the component shows up
4. Check that it clears the filters!
5. Try other combinations of filters 
- Is it safe to assume that the filters can all be set to null? 
- Does it work ok?
> Add empty table response

- frontend/src/APIClients/queries/StoryQueries.ts
- frontend/src/components/admin/AssignedStoryTranslationsTable.tsx
- frontend/src/components/pages/UserProfilePage.tsx
- frontend/src/utils/Utils.ts
build back better
[Dummy Assigned Stories Table](https://www.notion.so/uwblueprintexecs/Create-dummy-Assigned-Story-Translations-table-7967d4c1605749498d1d4529dc0c3de0)
- Create new table component to display Assigned Story Translations for a user on user page 
- Create new GQL query string to get story translations by user id 
1. Go to admin page and click on any user 
2. Ensure that their story translations / reviews are properly displayed 
- Styling is correct, entries in table are correct
> create dummy assigned story_translations_table (Taylor's version)

- frontend/src/components/admin/ApprovedLanguagesTable.tsx
- frontend/src/components/admin/AssignedStoryTranslationsTable.tsx
- frontend/src/components/pages/UserProfilePage.tsx
- frontend/src/utils/Utils.ts
https://www.notion.so/uwblueprintexecs/Create-dummy-Approved-Languages-Levels-table-5de91af7e3064d70b10e6dade6133b6b
- Created new table component to display user's Approved Languages & Levels
- Created a dummy slider
1. Login to angela merkel and go to any `/user/:id`
2. Ensure that the table looks correct
- Does the slider look okay?
- Does the sorting work?
> Implement dummy approved languages table

- frontend/src/components/admin/ApprovedLanguagesTable.tsx
- frontend/src/components/translation/FontSizeSlider.tsx
- fix slider button contrast for approved languages table and font size slider
1.
-
> Fix slider contrast

- .circleci/config.yml
- README.md
- Change command to `git ftp push ...` instead of `git ftp init`, as a follow up to #158 
- This was necessary to sync the git log file on the server with the main branch commit's 
1. Does this pass https://app.circleci.com/pipelines/github/uwblueprint/planet-read/1242/workflows/c72ec32d-ebea-494b-b101-d989d6c7fcd5
-
> Use git ftp push instead of init

- backend/python/app/services/implementations/story_service.py
- frontend/src/components/pages/ManageStoryTranslationPage.tsx
[Display translatorName and reviewerName in ManageStoryTranslationPage](https://www.notion.so/uwblueprintexecs/Display-translatorName-and-reviewerName-in-ManageStoryTranslationPage-62793d5d5d874586b0be692f2cda6f57)
- Modified get_story_translation query
- Minor fix for frontend (removed id so it only displays the name)
1. View Manage Story Translation page
- format of names in the query itself
> Display reviewer and translator names on manage story translation page

- backend/python/app/graphql/mutations/user_mutation.py
- backend/python/app/graphql/schema.py
- backend/python/app/graphql/types/user_type.py
- backend/python/app/services/implementations/user_service.py
[Add gql mutation to update user profile ](https://www.notion.so/uwblueprintexecs/Add-gql-mutation-to-update-user-profile-3bb87ef76ece4c1c94fa6550b238a14f)
- added a new gql for users to update their own profiles 
- Currently getting the user id in the graphql stage and passing, since importing the auth middleware into user_service creates a circular dependency -- would there be a better way to do this?
- require authentication for the update user by ID mutation (for admin)
1. Go to altair / or some other graphql gui 
2. Login as a [User](http://localhost:5000/graphql?variables=null&operationName=undefined&query=%0Amutation%20%7B%0A%20%20login%20(email%3A%22planetread%2Bmiroslavklose%40uwblueprint.org%22%2C%20password%3A%22dolphins_are_cool%22)%20%7B%0A%20%20%20%20accessToken%0A%20%20%20%2 …
> Update User Profile

- backend/python/app/services/implementations/story_service.py
- frontend/src/APIClients/mutations/StoryMutations.ts
- frontend/src/APIClients/queries/StoryQueries.ts
- frontend/src/components/admin/AssignedStoryTranslationsTable.tsx
- frontend/src/components/pages/UserProfilePage.tsx
- frontend/src/components/utils/AssignStoryModal.tsx
- frontend/src/components/utils/InfoAlert.tsx
- frontend/src/constants/Enums.ts
- frontend/src/constants/Roles.ts
- frontend/src/utils/Copy.ts
- frontend/src/utils/Utils.ts
[Ticket](https://www.notion.so/uwblueprintexecs/Implement-Assign-new-story-flow-d09abaf754ee453985c4db4aab180ad5)
- implement assign story modal + flow
- added check to assign_user_as_reviewer to prevent translator and reviewer being the same user
- To assign a user, go to localhost:3000/user/:id and click "Assign New Story"
- Feel free to test any of the flows below or any other combination!
While playing around with the modal, verify that:
1. all other fields are disabled before role is selected
2. story field is disabled if the other fields aren't selected
3. only approved languages/levels are displayed
1. Go to /user/4 and click "Assign New Story"
2. select "Reviewer", "English (UK)", "3", and "A Tale of Two Cities"
3. after confirming, verify that the page reloads and the new row …
> Implement assign story flow

- backend/python/app/graphql/mutations/story_mutation.py
- backend/python/app/graphql/schema.py
- backend/python/app/services/implementations/story_service.py
- frontend/src/APIClients/mutations/StoryMutations.ts
- frontend/src/components/admin/AssignedStoryTranslationsTable.tsx
- frontend/src/utils/Copy.ts
[Ticket](https://www.notion.so/uwblueprintexecs/Remove-user-from-story-translation-on-Assigned-Story-Translations-Table-120f15751a3b40248c1bbe4c8fdc389f)
- added gql mutation to remove a reviewer from a story translation
- if the user is a translator, soft delete story translation - otherwise unassign user as reviewer
1. Log in as angela merkel
2. Go to any `/user/:id`
3. In the "Assigned Story Translations" table, click the delete icon on any row (try both Translator and Reviewer rows)
4. After confirming, verify that the page reloads and the row is gone
- does the delete flow work for both Translator and Reviewer rows?
> Remove user from story translation

- frontend/src/components/pages/TranslationPage.tsx
- frontend/src/components/translation/TranslationTable.tsx
[Ticket](https://www.notion.so/uwblueprintexecs/Modify-translation-platform-to-accommodate-story-translation-tests-909f4e2dd1ad49c286f79fa956e021ab)
- added `isTest` state to toggle comment panel and status column in `TranslationPage.tsx`
1. Go to `translation/1/1`
2. Verify that the translation page looks as usual
3. Change [this line](https://github.com/uwblueprint/planet-read/blob/3942e826245627b790b221b038934e92e6011452/frontend/src/components/pages/TranslationPage.tsx#L58) to `useState(true)`
4. Verify that the comment panel and status column are gone 
- does it look okay?
> Modify translation page to accommodate story tests

- frontend/src/APIClients/mutations/UserMutations.ts
- frontend/src/components/admin/ApprovedLanguagesTable.tsx
- frontend/src/components/pages/UserProfilePage.tsx
- frontend/src/components/utils/InfoAlert.tsx
[:3 ](https://www.notion.so/uwblueprintexecs/Make-Approved-Languages-Levels-table-functional-e772071c9f3c422584afa806bb680b1a)
- Make sliders functional by calling GQL mutation to update user approved language level 
- Add alert to indicate to admin that level for user has been updated 
1. Go to User Profile page 
2. Change the levels for that user 
3. Refresh page, ensure changes persist 
4. Ensure that alert pops up when a level gets updated and the alert disappears after a few 
- Sliders functionality 
- Alerts show up when appropriate
> make approved languages table functional

- backend/python/app/middlewares/auth.py
- backend/python/app/services/implementations/story_service.py
- backend/python/migrations/versions/04653332ed3a_add_story_test_changes.py
[Modify updateStoryTranslationContents to enable story test grading ](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=c01b210ef2cd410688ba5d15669c5080)
- modified update_story_translation_content_status
- modified require_authorization_as_story_user_by_role to always authorize admins. IMO makes sense to give them full control of story translations. this also allows them to grade freely
- found a bug in the migrations - the status column enum wasnt getting updated. added a fix
set up
3. [make a new story …
> Modify updateStoryTranslationContents for grading

- backend/python/app/graphql/queries/story_query.py
- backend/python/app/graphql/schema.py
- backend/python/app/graphql/types/story_type.py
- backend/python/app/services/implementations/story_service.py
- backend/python/app/services/interfaces/story_service.py
- backend/python/app/tests/helpers/story_translation_helpers.py
- backend/python/app/tests/services/test_story_service.py
[Retrieve storyTranslationsTests](https://www.notion.so/uwblueprintexecs/Retrieve-storyTranslationsTests-03c53ae24da54cf6888f71b72d648472)
- implemented get_story_translation_tests query
- removed unused fields from StoryTranslationNodeDTO
Reset data:
Make new story translation tests:
1. [make test for user 1](http://localhost:5000/graphql?query=mutation%20CreateStoryTranslationTest%20%7B%0A%20%20createStoryTranslationTest(userId%3A%201%2C%20level%3A2%2C%20language%3A%22FRENCH%22)%7B%0A%20%20%20%20story%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20translatorId%0A%20%20%20%20%20%20storyId%0A%20%20%2 …
> Create get_story_translation_tests query

- frontend/src/components/admin/ApprovedLanguagesTable.tsx
- frontend/src/components/pages/CompleteProfilePage.tsx
- frontend/src/components/pages/UserProfilePage.tsx
- frontend/src/components/userProfile/AssignedStoryTranslationsTable.tsx
- frontend/src/components/userProfile/UserProfileForm.tsx
[Add user's personal user page](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=c672742600084570b18b3b3ee32bc778)
- UserProfilePage displays differently depending on if the user viewing the page is an admin or a user
- only ui change for admin page: theres an extra empty box between the `AssignedStoryTranslationsTable` and its title
- there are multiple changes to the page for when the user is viewing themselves
- viewing userid that isnt the users' own will redirect to a 404
- the UserProfileForm has been extracted from the CompleteUserProfile page. It is now used in the UserProfilePage too
- Approved Languages & Levels
- the action column is now for leveling up (button does nothing) 
- note: designs suggested moving the new …
> Add user's personal user page

- backend/python/tools/insert_test_data.py
The client accidently gave me the same document for levels 2 and 3 story tests. He gave me the correct level 3 story test, and this pr updates information accordingy
3. log in as carl sagan and browse for English UK, level 2, as translator on the homepage
4. observe the new story 
- does it work
> Correct level 3 story test in insert script

- frontend/src/APIClients/queries/StoryQueries.ts
Super quick PR for removing unneeded fields on the storyTranslations query as a result of [this change](https://github.com/uwblueprint/planet-read/pull/198/files#diff-d088b1642ca207d14aa58b53ccebff41b7d7f5111da99d8514131628fb4857b2L95)
Currently the story translations don't load on `/admin`, this fixes it
> [Hotfix] Remove unused storyTranslations query fields on the frontend

- backend/python/app/graphql/mutations/story_mutation.py
- backend/python/app/graphql/schema.py
- backend/python/app/models/story_translation_all.py
- backend/python/app/services/implementations/story_service.py
- backend/python/migrations/versions/04653332ed3a_add_story_test_changes.py
[Finish grading a story translation](https://www.notion.so/uwblueprintexecs/Finish-grading-a-story-translation-3e1114e9235c49ad8aebd0847f14938a)
- Added mutation that takes test_result, test_feedback, and story_translation_test_id params
- Check that translate and review are in the test_result param
- Calculate the test grade (correct = +1, partially correct = +0.5, others = none)
2. `docker exec -it planet-read_py-backend_1 /bin/bash -c "flask db downgrade"`  
3. `docker exec -it planet-read_py-backend_1 /bin/bash -c "flask db upgrade"`
4.  `docker exec -it planet-read_py-backend_1 /bin/bash -c "python -m tools.insert_test_data"`
2. [Login as admin and set …
> Add mutation to finish grading test story translation

- backend/python/app/graphql/mutations/comment_mutation.py
- backend/python/app/graphql/mutations/story_mutation.py
- backend/python/app/graphql/mutations/user_mutation.py
- backend/python/app/graphql/queries/story_query.py
- backend/python/app/middlewares/auth.py
- backend/python/app/services/implementations/comment_service.py
- backend/python/app/services/implementations/story_service.py
- services like create_comment are hard to unit test because the burden of authenticating the user is on the service rather than gql. moving the authentication to GQL adds clarity to responsibilities between moduals and also makes services easier to test
1. log in as carl sagan
2. go into a story translation
3. type text (tests story update service)
4. leave comments (tests comment service)
- does it work 
- does it make sense
> Move authentication to GQL

- frontend/src/App.tsx
[Redirect admins to / from /admins](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=f1209e12d6724adcb2b571af9d8f24a9)
- check if user is admin in App.tsx
- display Homepage at root if not admin. else display AdminPage
1. log in as angelamerkel
2. observe that youre directed to the admin page
3. login as carlsagan
4. observe that youre directed to the homepage
5. attempt going to /404, observe the 404
- does it work
> Redirect admins to / from /admins

- backend/python/tools/insert_test_data.py
- frontend/src/components/homepage/PreviewModal.tsx
- frontend/src/components/pages/TranslationPage.tsx
- frontend/src/components/translation/EditableCell.tsx
- frontend/src/components/translation/TranslationTable.tsx
- frontend/src/utils/LanguageUtils.ts
[Correct behaviour for right-to-left languages](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=65a0b13638174abeb19f7addc87c5893)
if the translated language is a rtl language, 
-  set the dir attribute on the `EditableCell` to rtl
- right align the cell text for the translated language column
if the translated language is a ltr language, everything behaves as usual
The insert script has been modified to contain an Arabic translation to test this feature.
1. open http://localhost:3000/ and log in as planetread+**richardfeynman**@uwblueprint.org
Left to right languages
2. view english translation "East of Eden" and observe that EditableCells behave as expected. type some stuff
3. submit translation for review and observe that text …
> Correct behaviour for right-to-left languages

- backend/python/app/graphql/types/story_type.py
- frontend/src/APIClients/queries/StoryQueries.ts
- frontend/src/components/admin/StoryTranslationsTable.tsx
[Add last edited column to StoryTranslationsTable](https://www.notion.so/uwblueprintexecs/Add-last-edited-column-to-StoryTranslationsTable-e03de6729fd94c339b3c00f12cc98e35)
- modified storyTranslations query and DTO to fetch last activity for translator and reviewer
- added column in StoryTranslationsTable to show last edited time
1. login as planetread+carlsagan@uwblueprint.org
2. go to translation for "To Kill A Mockingbird"
3. make some edits
4. login as planetread+angelamerkel@uwblueprint.org
5. verify that the "To Kill a Mockingbird" row for Carl Sagan shows the last edited timestamp
6. click on the "To Kill a Mockingbird" link in the row
7. verify that the last edited column appears in the story page also
- is there a more optimal way to check for the most recent date?
> Add last edited column to story translations table

- frontend/src/components/admin/ApprovedLanguagesTable.tsx
- frontend/src/components/admin/TableFilter.tsx
- frontend/src/components/pages/UserProfilePage.tsx
- frontend/src/components/userProfile/AssignedStoryTranslationsTable.tsx
- frontend/src/components/utils/ApproveLanguageModal.tsx
- frontend/src/theme/components/Select.ts
[Implement approved language table "Add new level" flow](https://www.notion.so/uwblueprintexecs/Implement-approved-language-table-Add-new-level-flow-41bb51999eed4359976809f465787060)
- implemented approve new language flow, including new modal
- minor adjustments to keep both info alert behaviours on UserProfilePage consistent
2. Go to any `/user/:id`
3. Click "Add New Language"
4. Select a role and verify that only new languages appear (not ones that the user is already approved for)
5. Select a level and click "Assign"
6. Verify that the new language appears in the table properly
- does the modal work?
- does the new row get inserted properly?
- verify that the info alert displays the correct information and behaves consistently with the "Assign New Story" flow
> Implement admin approve new language flow

- frontend/src/components/review/CommentsPanel.tsx
[Make the default comment filter unresolved](https://www.notion.so/uwblueprintexecs/Make-the-default-comment-filter-unresolved-63bdde5306204af9820b1aa9975f9450)
- change default filter index to "Unresolved"
1. Login as any user
2. Go to any story translation
3. Verify that the default filter is "Unresolved"
-
> Change default comment filter to "Unresolved"

- frontend/src/components/pages/ReviewPage.tsx
- frontend/src/components/pages/TranslationPage.tsx
[Redirect user to homepage after story translation stage change](https://www.notion.so/uwblueprintexecs/Redirect-user-to-homepage-after-story-translation-stage-change-c1828eca207b483caf6baad2ac50fd82)
- replace `window.location.reload()` with `history.push("/")`
1. Login to any user
2. Go to any story translation and click the bottom right button to update story translation stage
3. Observe redirect to homepage
> Redirect to homepage after story translation stage change

- backend/python/app/services/implementations/story_service.py
- frontend/src/APIClients/queries/StoryQueries.ts
- frontend/src/components/homepage/StoryCard.tsx
- frontend/src/components/homepage/StoryList.tsx
- frontend/src/components/pages/HomePage.tsx
[Add My Tests tab on homepage](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=67ced17704474f09ba244adeff4eafab)
- add new GQL query to call the `StoryTranslationTests` mutation 
- create new tab on homepage to display tests 
- Slight modifications to story card to correctly display information for a story test 
1. Go to home page, sign in as Angela Merkel 
2. Create a new story translation test using [this link](http://localhost:5000/graphql?query=mutation%20%7B%0A%20%20createStoryTranslationTest(userId%3A%201%2C%20level%3A2%2C%20language%3A%22FRENCH%22)%7B%0A%20%20%20%20story%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20translatorId%0A%20%20%20%20%20%20storyId%0A%20%20%20%20%20%20language%0A%20%20%20%20%20%20stage%0A%20%20%20% …
> Add My Tests tab on homepage

- backend/python/app/services/implementations/story_service.py
- frontend/src/APIClients/queries/StoryQueries.ts
- frontend/src/components/admin/ManageStoryTests.tsx
- frontend/src/components/admin/StoryTestsTable.tsx
- frontend/src/components/navigation/Header.tsx
- frontend/src/components/pages/AdminPage.tsx
- frontend/src/components/pages/StoryTestGradingPage.tsx
- frontend/src/utils/Copy.ts
[Create Manage Tests admin page](https://www.notion.so/uwblueprintexecs/Create-Manage-Tests-admin-page-32dbf205f61e4e94822aef4b22dce5fc)
- created table to display story translation tests that have been submitted (in REVIEW)
- fix grading page to allow admin access
- fix soft_delete_story_translation mutation to handle deletion of story tests
3. create a few story translation tests using the mutation below
4. on Altair, login as Carl Sagan and update story test stage using the mutation below
5. login as Angela Merkel and go to `/admin`
6. click on "Manage Tests" and verify that only the story test …
> Create admin "Manage Tests" page

- frontend/src/components/homepage/Filter.tsx
- frontend/src/theme/components/Filter.ts
[Do not display filters in “My stories” homepage](https://www.notion.so/uwblueprintexecs/Do-not-display-filters-in-My-stories-homepage-545d5c55b6634a4889bd26f35931f04d)
- hide filters on "My Work" tab
- adjust filter component styling to have a sufficient minimum height
1. Login as any user
2. observe that the filters are hidden on the "My Work" section
3. verify that filters appear and are functional in the "Browse Stories" section
> Hide filters when displaying user's stories

- backend/python/app/services/implementations/story_service.py
- frontend/src/APIClients/mutations/StoryMutations.ts
- frontend/src/components/admin/ApprovedLanguagesTable.tsx
- frontend/src/components/admin/ApprovedLanguagesTableComponent.tsx
- frontend/src/components/utils/ConfirmationModal.tsx
- frontend/src/utils/Copy.ts
[Implement level up language flow](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=2ca8903a499a4d5bb6b0cb978762d26c)
- moved the table jsx and specific logic to ApprovedLanguagesTableComponent
- added confirmation modals for leveling up language, and notifying users to move to homepage
1. login as carl sagan
2. go to user profile 
3. hit level up button 
4. observe that flow exists
5. hit level up button again 
6. observe error `Error: User has an ongoing story translation test for language [abcd].`
7. fail the story translation test to observe the other error.  You'll need to do this in altair as an admin:
```
mutation {
finishGradingStoryTranslation(storyTranslationTestId: 14, testFeedback: "blah", testResult: "{}"){
ok …
```
> Implement level up language flow

- backend/python/app/services/implementations/comment_service.py
- frontend/src/components/review/StatusBadge.tsx
[Allow action status to be manually assigned, remove comment services involvement in statuses](https://www.notion.so/uwblueprintexecs/Allow-action-status-to-be-manually-assigned-remove-comment-services-involvement-in-statuses-c111880833024646870e0ddf31e2b41e)
- add "ACTION_REQUIRED" option to status badge dropdown
- remove `story_translation_contents.status changes` from comment_services
3. change story translation to review using `UPDATE story_translations SET stage='REVIEW' WHERE id=13;`
4. login as `planetread+dwightdeisenhower@uwblueprint.org`
5. click "View Translation" on "The Great Gatsby" …
> Allow more action status flexibility in review page

- frontend/src/components/review/ExistingComment.tsx
[Do not display ‘resolve’ button if comment is resolved](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=f90370003fb141fdb6df223da412fe56)
- Make the resolve button only display if comment is not resolved 
1. Create a comment 
2. Resolve comment, button should disappear
- Not much, small PR
> Do not display ‘resolve’ button if comment is resolved

- frontend/src/components/review/ExistingComment.tsx
[Display local timezone and code on comments](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=e40faef97e14495ea2a8d7eb18af7685)
- Change displayed time to use the local offset
1. Create a comment 
2. Make sure it displays the same timezone as your computer 
3. read [this article](https://www.economist.com/leaders/2020/10/29/why-it-has-to-be-biden)
- Timezone works for your local system
> Display Local Time on comments 

- backend/python/app/services/implementations/user_service.py
- frontend/src/components/admin/ApprovedLanguagesTable.tsx
- frontend/src/components/admin/ApprovedLanguagesTableComponent.tsx
- frontend/src/utils/Copy.ts
[Implement remove approved language flow](https://www.notion.so/uwblueprintexecs/Implement-remove-approved-language-flow-802140979e214faf9bae4bccbeba3f98)
- modified `updateApprovedLanguage` mutation to support language deletion
- implemented language deletion flow in `ApprovedLanguagesTable.tsx`
2. Go to any `/user/:id`
3. On any row in the "Approved Languages" table, click the action icon 
4. Verify that the delete language flow works and that the proper info alert displays after confirmation
5. Verify that the row is removed from the table
6. Login as any other user and go to profile page
7. observe that the action column doesn't have the same button as admin
- does the flow work and is it intuitive?
> Implement remove language flow

- backend/python/tools/insert_test_data.py
- ids got offset by 10 due to changes inserted story translations + tests
3. log in as carl sagan and see that the Great Gatsby comments look lit
- does it work
> Fix insert comments story_translation_content_ids

- frontend/src/components/admin/ApprovedLanguagesTableComponent.tsx
- oops, shouldve caught this in the last pr. we're sticking to the trash icon through out the web app, but some of the designs are old and use the wrong icon
1. 
garbage 🗑️ 
- does it look lit
> Fix: use delete icon for deleting languages

- frontend/src/APIClients/queries/StoryQueries.ts
[My test tab on homepage should not show INREVIEW/ PUBLISHED tests](https://www.notion.so/uwblueprintexecs/My-test-tab-on-homepage-should-not-show-INREVIEW-PUBLISHED-tests-cec3ba26e46d4ed6b4856d6eb6796f81)
- Added `stage: TRANSLATE` argument to `storyTranslationTests` query in `buildHomePageStoriesQuery`
1. Login as Carl (or anyone who can level up a language)
2. Go to profile and level up a language
3. Verify that a new test shows up under My Tests tab
4. Send the test for review
5. Verify that the test is no longer shown under My Tests tab
6. Publish the test by updating the row using mysql: `UPDATE story_translations set stage="PUBLISH" where id=14;`, or by using Altair as admin:
```
mutation {
finishGradingStoryTranslation(storyTranslationTestId: 14, testFeedback: "blah", testResult: …
```
> My test tab on homepage should not show INREVIEW/ PUBLISHED tests

- frontend/src/APIClients/queries/CommentQueries.ts
- frontend/src/APIClients/queries/StoryQueries.ts
- frontend/src/components/pages/ReviewPage.tsx
- frontend/src/components/pages/TranslationPage.tsx
- frontend/src/components/review/CommentsPanel.tsx
- frontend/src/components/review/ExistingComment.tsx
https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=b9f8e51d62604951a5a7831233697b91
- retrieve translatorName and reviewerName from backend
- use the correct name in ExistingComments
- (note: did not change WIPComments because the name is always the authenticatedUser Name)
1. login as carl sagan
2. see great gatsby 
3. wow look at all those names 
4. log in as dwight and look at same translation
5. the names better match up!
- does it work
> Display correct user names on comments

- backend/python/app/services/implementations/comment_service.py
- frontend/src/components/pages/ReviewPage.tsx
- frontend/src/components/pages/TranslationPage.tsx
- frontend/src/components/review/CommentsPanel.tsx
[Remove non PUBLISHED comment stage restrictions](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=38538489e17b4470afb3369b39e423a7)
- Remove the first two restrictions
1. Reviewers and commenters should be able to leave comments on a story regardless of what stage it is in
- idk, living a happy and meaningful life?
> Remove non PUBLISHED comment stage restrictions

- frontend/src/components/admin/Statistic.tsx
> Change flexGrow to number 

- frontend/src/components/admin/StoryTestsTable.tsx
[MyTest table user link uses story_translation_id instead of user_id](https://www.notion.so/uwblueprintexecs/MyTest-table-user-link-uses-story_translation_id-instead-of-user_id-ad2fa10b2c4b46d4b3b0bc52d7ff0f2b)
- Use translatorId instead of id
1. Login as admin and go to http://localhost:3000/ 
2. Check that clicking on the name brings you to the correct profile
- Does it work
> Link to user instead of translation 

- backend/python/app/graphql/types/story_type.py
- backend/python/app/services/implementations/story_service.py
- frontend/src/APIClients/queries/StoryQueries.ts
- frontend/src/components/pages/TranslationPage.tsx
- get is_test from the backend for the story translation on the TranslationPage
- hid panel (actually already implemented, yay!) 
1. login as carlsagan
2. observe that non-test story translations still have their comments
3. make a test 
```
mutation { createStoryTranslationTest(userId: 1, level: 2, language: "GERMAN") {
story {
id
}
}
}
```
4. observe the missing comment panel
5. send for review and observe the still missing comment panel
- anyother edge cases?
> Hide comment panel for tests

- backend/python/app/services/implementations/comment_service.py
- frontend/src/components/review/ExistingComment.tsx
https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=88d025db50c24db5a3544e520060539d
- in service, resolve all comments for a translation content id
- only display resolve button at head of thread  
- resolving any part of the thread works but the ui is a little confusing if you can resolve in thread
- do not display reply button if resolved 
1. log in as carl sagan and look at the great gatsby
2. resolve a comment. observe the entire thread disappears
3. set the comment filter to resolved. note the lack of reply and resolve buttons
- does it work and make sense
> Resolve entire thread when comment resolved

- frontend/src/components/utils/ProgressBar.tsx
- frontend/src/utils/Utils.ts
https://www.notion.so/uwblueprintexecs/Truncate-progress-number-54e778e01a2742fd9ed32c9d2b326529
- added util function to truncate decimal number
1. Login to any user
2. Go to profile page and click any "Level up" button
3. Go to story test and edit translation, verify that the decimal numbers are truncated
- verify that the whole numbers don't display 2 decimals
> (Bugfix) Truncate progress value to 2 decimal places

- backend/python/app/graphql/mutations/story_mutation.py
- backend/python/app/graphql/types/story_type.py
- backend/python/app/services/implementations/story_service.py
- backend/python/app/services/interfaces/story_service.py
- backend/python/app/tests/services/test_story_service.py
- frontend/src/APIClients/mutations/StoryMutations.ts
- frontend/src/APIClients/queries/StoryQueries.ts
- frontend/src/components/homepage/StoryCard.tsx
- frontend/src/components/userProfile/AssignedStoryTranslationsTable.tsx
- frontend/src/components/utils/ApproveLanguageModal.tsx
https://www.notion.so/uwblueprintexecs/Update-Assigned-Story-Translations-state-dd7f387197524954966b4a64cb903529
- modfiied return types for createStoryTranslation and assignUserAsReviewer mutations to return story translation object
- update local state when new story translation is assigned
- modified condition in `assign_user_as_reviewer` to accept case where translation isn't in TRANSLATE stage
1. login as admin, go to /user/4
2. click "assign new story"
3. select Translator, English (US), Level 2, Nineteen Eighty-Four
4. verify that new story translation is assigned and the row appears (observe no refresh)
5. click "assign new story" again
6. select Reviewer, English (UK), Level 3, A Tale of Two Cities
7. verify that row appears
8. delete both rows, verify that it works
- does it …
> Update local state when assigning new story translation

- frontend/src/APIClients/mutations/StoryMutations.ts
- frontend/src/components/pages/StoryTestGradingPage.tsx
[Implement Fail Grade flow](https://www.notion.so/uwblueprintexecs/Implement-Fail-Grade-flow-078ae20bdcbd437c89c093df93a41068)
- added the finishGradingStoryTranslation mutation 
- added a function to fail the test 
1. [Create a story translation test](http://localhost:5000/graphql?variables=null&operationName=CreateStoryTest&query=mutation%20CreateStoryTest%20%7B%0A%20%20createStoryTranslationTest(userId%3A%201%2C%20level%3A2%2C%20language%3A%22FRENCH%22)%7B%0A%20%20%20%20story%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20translatorId%0A%20%20%20%20%20%20storyId%0A%20%20%20%20%20%20language%0A%20%20%20%20%20%20stage%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D) 
2. login as angela merkel 
3. in console set the stage to `REVIEW` (`update story_translations set stage=2 where id = ... ;`)
4. go to …
> Implement fail test flow

- backend/python/app/graphql/queries/story_query.py
- backend/python/app/graphql/schema.py
- backend/python/app/services/implementations/story_service.py
- backend/python/app/services/interfaces/story_service.py
- frontend/src/APIClients/queries/StoryQueries.ts
- frontend/src/components/userProfile/AssignedStoryTranslationsTable.tsx
- frontend/src/components/utils/AssignStoryModal.tsx
https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=fc6fd704b0674be19c756b4a1c30ef6c)
- swapped out `_get_story_translations_user_translating` and `_get_story_translations_user_reviewing` for flexible query builder
- added checks to `get_stories_available_for_translation `and `get_story_translations_available_for_review`
- if there exists ongoing story translations with same language+role for user, return []
- this could be swapped with an error message that could be displayed, but the designs for that are TBD.
- passed in user_id for admin's UserProfile view to relative mutations
1. login as planetread+dwightdeisenhower@uwblueprint.org
2. observe ongoing no English US, but ongoing English UK and German translations.
3. go to browse …
> Don’t return story translations if user already translating/reviewing for language

- frontend/src/components/admin/ApprovedLanguagesTable.tsx
- frontend/src/components/admin/ApprovedLanguagesTableComponent.tsx
- frontend/src/utils/Copy.ts
[Implement demoting language level flow](https://www.notion.so/uwblueprintexecs/Implement-demoting-language-level-flow-4f23433446704bda876f4c1f3bc9846a)
- show modal when admin attempts to demote user's approved level
2. Click on any user page (http://localhost:3000/#/user/:id)
3. Move the slider to a lower approved level for a translation language
4. Confirm that confirmation modal shows up
5. Close the modal and confirm the approved level is unchanged and no gql calls were made
6. Move slider to a lower approved level for a translation language again
7. Confirm that confirmation modal shows up, and click `I'm sure, lower level`
8. Verify that approved language is lowered
9. Repeats steps 3-8 for a review language
___Sanity Checks:___
10. Confirm that you can still …
> Implement demoting language level flow

- backend/python/app/graphql/queries/file_query.py
- backend/python/app/graphql/schema.py
- backend/python/app/graphql/types/file_type.py
- backend/python/app/services/implementations/file_service.py
- backend/python/app/services/interfaces/file_service.py
https://www.notion.so/uwblueprintexecs/Download-files-via-fileById-cce5b4acf4b0455981e6452e294eec77
- implement `fileById` query by converting file data to a base64 string and returning it in a `DownloadFileDTO`
1. start docker containers
2. in any directory, run `curl http://localhost:5000/graphql -F operations='{"query": "mutation ($file: Upload!) { createFile(file: $file) { ok }}", "variables": {"file": null }}' -F map='{ "0": ["variables.file"]}' -F 0=@file_name.txt`, replacing `file_name.txt` with any file in the directory to upload the file
3. in Altair, login as any user and run the query below
4. verify that the query succeeds and the file string is returned
5. if you want to verify that the string encoded properly, copy and run the following code in `codesandbox.io`
```
// …
```
> Download files via fileById

- frontend/src/APIClients/queries/StoryQueries.ts
- frontend/src/components/admin/StoriesTable.tsx
- story link on manage stories table works now
- couldnt find any other hrefs that dont follow our new /#/ pattern
- homepage loads correctly. There is no dateUploaded field on the StoryTranslationDTO but I accidentally included it on #243 
1. login as angela
2. manage stories
3. click links
4. profit
5. login as carl/any user
6. load homepage
7. profit
- is it lit
> Fix: correct story table link and stories query

- backend/python/app/graphql/mutations/file_mutation.py
- backend/python/app/graphql/mutations/user_mutation.py
- backend/python/app/services/implementations/file_service.py
- backend/python/app/services/implementations/user_service.py
[Upload user’s resume](https://www.notion.so/uwblueprintexecs/Upload-user-s-resume-df9deacce79b41bda5907e9605a29150)
- Moved the folder path logic to create_file 
- Allow users to upload a resume when in UpdateMe mutation
1. Login as a user and copy the access token ([i.e. carl sagan](http://localhost:5000/graphql?variables=null&operationName=undefined&query=%0Amutation%20%7B%0A%20%20login%20(email%3A%22planetread%2Bcarlsagan%40uwblueprint.org%22%2C%20password%3A%22%22)%20%7B%0A%20%20%20%20accessToken%0A%20%20%20%20refreshToken%0A%20%20%20%20id%0A%20%20%7D%0A%7D))
2. Using your access token and a path to a file, try `curl http://localhost:5000/graphql -F operations='{"query": "mutation ($file: Upload!) { updateMe(resume: $file, user:{firstName: \"Carl\", lastName: \"Sagan\", …
> Allow users to upload resume

- frontend/package.json
- frontend/src/APIClients/queries/FileQueries.ts
- frontend/src/APIClients/queries/UserQueries.ts
- frontend/src/components/pages/UserProfilePage.tsx
- frontend/src/theme/components/Button.ts
- frontend/src/utils/FileUtils.ts
- frontend/yarn.lock
https://www.notion.so/uwblueprintexecs/Enable-admin-to-download-resume-f1ddd118506b466b8e33b1b376ee8467
- add "User files" sidebar section to `UserProfilePage.tsx` for admins
- implement utility functions to download files
- created `useFileDownload` hook to encapsulate generic file download logic
for backend implementation, see https://github.com/uwblueprint/planet-read/pull/244
1. `docker-compose up --build`
2. Upload a few files (ideally pdf) using curl: `curl http://localhost:5000/graphql -F operations='{"query": "mutation ($file: Upload!) { createFile(file: $file) { ok }}", "variables": {"file": null }}' -F map='{ "0": ["variables.file"]}' -F 0=@file_name.pdf`
3. set resume of carl sagan to file id: `docker exec -it planet-read_db_1 mysql -u root -proot -e "UPDATE users SET …
> Enable admin to download resume

- frontend/src/components/pages/NewLanguageModal.tsx
- frontend/src/components/pages/UserProfilePage.tsx
[Implement add new language flow for users](https://www.notion.so/uwblueprintexecs/Implement-add-new-language-flow-for-users-3ac4368314d74d239b896d70ca7b1cd2)
- Created add new language modal for user to select a new language
- Adds a level 2 test for that language using create translation test mutation
- Existing confirmation modal is used to redirect user to homepage after test is added
1. Login as Carl (or another translator/reviewer)
2. Go to profile page
3. Click the add new language button
4. Hover over add test to see a tooltip
5. Select a language from the dropdown (verify that the drop down does not contain any already approved languages for translation)
6. Click add test
7. Click take me to homepage on the confirmation modal
8. Go to my tests tab and verify that the test has …
> Implement add new language flow for users

- frontend/src/components/review/CommentsPanel.tsx
- frontend/src/components/review/ExistingComment.tsx
- frontend/src/components/review/WIPComment.tsx
https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=802f3a1377064bd79778c2a4ec31b616
- defined and mapped comments to be thread heads or non thread heads
- styled comments accordingly 
- bonus: solved odd resolving behaviour 
A thread head is the beginning of a thread. it is not indented.
A live thread head is an unresolved thread head. it has a reply and resolve button. 
3. login as carlsagan and go to http://localhost:3000/review/6/13
4. set comment filter to all
5. observe resolved thread on line 1
6. make new comment on line 1
7. observe …
> Implement multi thread comment styling

- frontend/src/components/pages/UserProfilePage.tsx
[Remove useless cancel/save buttons on Admin view of UserProfile](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=512100b41a2845e6973cb4e128095646)
- Remove buttons in `UserProfilePage.tsx`
1. Go to user profile page and make sure there are no **Save** and **Cancel** buttons
- morality
> Remove useless cancel/save buttons on Admin view of UserProfile

- backend/python/app/services/implementations/story_service.py
- use StoryAll instead of story to get contents (translate/review platform couldnt load because contents was coming back null)
1. opn translation platform
2. observe that it works lol
- does it work
> Fix: use StoryAll in get_story to get contents

- frontend/src/components/pages/HomePage.tsx
- frontend/src/components/utils/ButtonRadioGroup.tsx
- frontend/src/utils/hooks/useQueryParams.tsx
https://www.notion.so/uwblueprintexecs/Enable-redirecting-to-specific-homepage-tab-41fe40b2d2dc424d9a0c4bb7170fa612
- refactored `HomePage.tsx` to use an enum for navigation instead of two booleans
- created hook to fetch URL query params
1. Login as any non-admin user
2. Click on the tabs to navigate between different pages, verify that the URL changes
3. Try entering `/?tab=1` or any other id, verify that the correct page is shown (My Work = 0)
4. Play around with the navigation, verify that it works as normal
- is ther any janky edge case behaviour?
> Enable redirecting to specific homepage tab

- backend/python/app/services/implementations/story_service.py
[assign_user_as_reviewer should not change story translation stage](https://www.notion.so/uwblueprintexecs/assign_user_as_reviewer-should-not-change-story-translation-stage-5f769d3cd38b48ad83dfa3c159585308)
- Removes line that sets story translation stage to review
1. Login as admin, grab auth token 
2. Try assigning a reviewer http://localhost:5000/graphql?variables=null&operationName=undefined&query=mutation%20%7B%0A%20%20assignUserAsReviewer(storyTranslationId%3A6%2C%20userId%3A4)%7B%0A%20%20%20%20story%7B%0A%20%20%20%20%20%20translatorId%0A%20%20%20%20%20%20stage%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D 
3. Check that story stage has not changed 
> Don't set stage when assigning reviewer

- frontend/src/components/homepage/Filter.tsx
https://www.notion.so/uwblueprintexecs/Remove-filter-component-shadow-when-filter-is-disabled-on-My-Work-My-Tests-3467406a468e44599431b7fc58903c1d
- remove box shadow if filter is disabled
1. Login as any user, verify that filter shadow doesn't show on "My Work" and "My Tests"
-
> Remove box shadow for filter if it's disabled

- frontend/src/APIClients/queries/UserQueries.ts
- frontend/src/components/pages/UserProfilePage.tsx
- frontend/src/theme/components/Heading.ts
- frontend/src/theme/components/Textarea.ts
- frontend/src/utils/Utils.ts
https://www.notion.so/uwblueprintexecs/Add-User-Background-section-to-admin-view-of-profile-page-19ec0e7c82e1491c9349e6aaaa662c08
- fetch additionalExperiences in `userById` query
- add User Background section in admin view of `UserProfilePage.tsx`
1. manually set user additional_experiences by going into the DB: `docker exec -it planet-read_db_1 /bin/bash -c "mysql -u root -proot"` and using: ```update users set additional_experiences = JSON_MERGE_PATCH(COALESCE(`additional_experiences`, "{}"), '{"languageExperience": "Test language experience string", "educationalQualification": "Test educational qualifications string"}') where id = 1;```
2. Login as admin and go to Carl Sagan's profile `/user/1`
3. Verify that user background section appears and appropriate strings are displayed
4. …
> Implement user background section on UserProfilePage

- frontend/src/components/navigation/Header.tsx
- frontend/src/components/pages/AdminPage.tsx
https://www.notion.so/uwblueprintexecs/Enable-redirecting-to-specific-admin-tab-7fa84a9e6015421892895c0647086af2
- implement redirecting to admin tab based on URL query param
2. Click through header tabs, verify that the URL changes
3. Try setting URL manually, verify that it works 
4. Sanity check: login as non-admin user and verify that header doesn't show admin tabs
> Enable redirecting to specific admin tab

- backend/python/app/graphql/mutations/comment_mutation.py
- backend/python/app/graphql/schema.py
- backend/python/app/services/implementations/comment_service.py
- backend/python/app/services/interfaces/comment_service.py
- backend/python/app/tests/helpers/comment_helpers.py
- backend/python/app/tests/services/test_comment_service.py
[Ticket ](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=d9efc1595f954086b7ece906ccdd62c4)
- Add unit tests for story service
- Remove `update_comments` mutation in `comment_service`
1. Read through unit tests, check that they make sense
2. Make sure nothing is broken after removing  `update_comments` mutation in `comment_service`
-
> Add unit tests for comment service

- frontend/src/components/pages/ManageStoryPage.tsx
Change order of page redirction and reload to be AFTER calling mutation
- I messed up the order in which we call the mutation and reload the page for soft deletes, oops
1. Soft delete story, make sure nothing breaks and you are redirected to the admin page
-
> HOTFIX: Soft Delete Stories

- backend/python/app/graphql/queries/file_query.py
- backend/python/app/graphql/queries/story_query.py
- backend/python/app/graphql/schema.py
- backend/python/app/graphql/types/file_type.py
- backend/python/app/services/implementations/file_service.py
- backend/python/app/services/implementations/story_service.py
- backend/python/app/services/interfaces/file_service.py
- frontend/src/APIClients/queries/FileQueries.ts
[Export Story Translation](https://www.notion.so/uwblueprintexecs/Export-Story-Translation-89e4d88148824aecb5e6e72f843775dc)
- creates a new word doc, saves to db, returns the encoded string, and then deletes the file 
1. Login as an admin (angela merkel) 
2. [Try this query](http://localhost:5000/graphql?variables=null&operationName=undefined&query=query%20%7B%0A%20%20exportStoryTranslation(id%3A2)%7B%0A%20%20%20%20file%0A%20%20%7D%0A%7D) - see if that returns an encoded string and that file got deleted
3. To see if the file actually saved correctly, (testing process is a little sus rn but) comment out line 53 in `story_query.py`
4. Get the file id for the document (should be the last row in the files table)
5. Set the resume for Carl Sagan to the new file (`update users set …
> Export story translation .docx

- frontend/src/components/pages/ReviewPage.tsx
- frontend/src/components/pages/TranslationPage.tsx
- frontend/src/components/review/CommentsPanel.tsx
- frontend/src/components/review/ExistingComment.tsx
- frontend/src/components/review/WIPComment.tsx
https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=bde38143a0bb45ebb08012c31f1a1d16
- rip out modifying storytranslationcontent stuff in the comment panel + its components 
1. log in as carl and open the great gatsby 
2. make new comments 
3. reply to comments
4. do other random comment things 
5. observe that statuses never change 
- does it work
> Fix: do not edit line status when creating comment

- backend/python/app/graphql/types/story_type.py
- frontend/src/APIClients/queries/StoryQueries.ts
- frontend/src/components/userProfile/AssignedStoryTranslationsTable.tsx
https://www.notion.so/show-User-Last-Edited-on-StoryTranslationTable-f413f04770164ec6a9bff4faa8021bb8
- fetch `translator_last_activity` and `reviewer_last_activity` on `storyTranslationsByUser` query
- display date in new column
1. Login as Carl Sagan
2. Go to "To Kill a Mockingbird" and make some changes
3. Login as admin
4. Go to carl sagan's profile `/user/1`
5. Verify that date appears in assigned story translations table
> Show User Last Edited on AssignedStoryTranslations table

- frontend/src/components/pages/UserProfilePage.tsx
- frontend/src/components/userProfile/AssignedStoryTranslationsTable.tsx
- frontend/src/constants/Enums.ts
- frontend/src/utils/Utils.ts
…slation
https://www.notion.so/uwblueprintexecs/Delete-story-translation-toast-on-Assigned-Story-Translations-table-does-not-appear-fda48ebff79b4b5a8b94b6c7fae189f2
- modified `StoryAssignStage` enum to handle user removal
- display alert and update local state after removing user from translation
2. Go to any user page
3. Remove user from any story translation
4. Verify that page does not reload and row is removed + appropriate alert is shown
> Show alert after removing user from story translation

- backend/python/app/services/implementations/file_service.py
- frontend/src/APIClients/queries/FileQueries.ts
- frontend/src/components/admin/StoryTranslationsTable.tsx
- frontend/src/components/pages/UserProfilePage.tsx
- frontend/src/utils/Copy.ts
- frontend/src/utils/FileUtils.ts
https://www.notion.so/uwblueprintexecs/Implement-export-story-translation-flow-4a0a41104fa647369290e77c128cf7a6
- added "export" column to `StoryTranslationsTable.tsx`, disabled if translation is not completed
- modified `useFileDownload` hook to make it more reusable
1. in the db, run `UPDATE story_translations set stage='REVIEW' where id=13;`
2. Login as `planetread+dwightdeisenhower@uwblueprint.org`
3. Mark all as approved and submit translation
4. Login as admin
5. Verify that export column appears in "Manage Story Translations" table
6. observe that exporting is disabled for all non-completed translations
7. go to page 2
8. click on export button in row with id = 13
9. observe story translation being exported!!
10. click on `The Great Gatsby` title and verify that the column appears …
> Implement export story translation flow

- frontend/src/components/onboarding/AssignTestGradeModal.tsx
- frontend/src/components/onboarding/FailUserModal.tsx
- frontend/src/components/onboarding/TestFeedbackModal.tsx
- frontend/src/components/pages/StoryTestGradingPage.tsx
https://www.notion.so/uwblueprintexecs/Add-feedback-modal-to-fail-grade-flow-4a2ca39f3279424a95fa4cb5ecae2170
- create `FailUserModal.tsx` to encapsulate fail user flow
1. Login to any user and start new story test
2. Submit for review
3. Login as admin and grade story test
4. Click "Fail user" and verify that feedback modal appears after clicking "I'm sure"
5. Play around with the flow (closing modals, confirmation, etc.)
> Add feedback modal to fail grade flow

- frontend/src/components/pages/ReviewPage.tsx
- frontend/src/components/pages/StoryTestGradingPage.tsx
[Disable SUBMIT TRANSLATION button if stage ≠ REVIEW](https://www.notion.so/uwblueprintexecs/Disable-SUBMIT-TRANSLATION-button-if-stage-REVIEW-97bcecb4df35421dbd3faa937d439b2b)
- Disable buttons for grading and submitting if the story stage is not REVIEW
1. Login as a translator and go to a story translation that you are reviewing 
2. Check that a story translation in the translation stage has a disabled submit translation button
3. Move the story to review, check that the button is enabled
4. Login as admin
5. Repeat the steps with a story test
> Disable buttons when stage is not review

- frontend/src/components/admin/UsersTable.tsx
- frontend/src/utils/Copy.ts
[tooltip](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=7165106552f34e67aab3905b6ef938f5)
- Add tooltip to delete user icon 
1. Go to admin page and see Manage Translators and Manage Reviewers 
2. Ensure that the tooltip is displayed when mouse hovers over the delete icon 
- theoretical computer science
> Add delete user tool tip on UserTable

- backend/python/app/graphql/mutations/user_mutation.py
- backend/python/app/services/implementations/user_service.py
- frontend/src/APIClients/mutations/UserMutations.ts
- frontend/src/components/pages/CompleteProfilePage.tsx
- frontend/src/components/pages/UserProfilePage.tsx
- frontend/src/components/userProfile/UserProfileForm.tsx
[Use updateMe mutation in CompleteProfilePage](https://www.notion.so/uwblueprintexecs/Use-updateMe-mutation-in-CompleteProfilePage-eb38376e72d94f0a9b19d726e95f45a7)
- Use the updateMe mutation to update user details based on form
1. Signup with a new user on the login page
2. Fill in details on the form
3. Verify user details are updated by checking the users_all and users tables in the database
- Mutation is implemented correctly
- Additional details field is properly set
- Ignore the if statement in the UsersProfilePage (placeholder to avoid linter error until its properly implemented)
> Add functionality to completeprofile page

- backend/python/app/graphql/queries/story_query.py
- backend/python/app/graphql/schema.py
- backend/python/app/graphql/types/story_type.py
- backend/python/app/services/implementations/story_service.py
- backend/python/app/services/interfaces/story_service.py
- frontend/src/APIClients/queries/StoryQueries.ts
- frontend/src/components/admin/ManageStoryTests.tsx
- frontend/src/components/admin/StoryTestsTable.tsx
- frontend/src/utils/Utils.ts
Last PR of 2021!!
https://www.notion.so/uwblueprintexecs/Modify-StoryTestTable-to-display-completed-tests-aac9883ed973401d96a81bd0194f7bcd
- modified query to optionally return story tests in REVIEW and PUBLISH
- display review progress in StoryTests table
1. Login as any user and start multiple story tests, submit for review
2. Login as admin and view the tests, play around with the grading flow
3. Verify that the review progress is reflected appropriately in the table
> Display completed story tests and review progress in StoryTestsTable

- frontend/src/components/review/CommentThread.tsx
- frontend/src/components/review/CommentsPanel.tsx
- frontend/src/components/review/ExistingComment.tsx
- frontend/src/components/review/WIPComment.tsx
[Open WIP comment under bottom of thread on reply](https://www.notion.so/uwblueprintexecs/Open-WIP-comment-under-bottom-of-thread-on-reply-18773f3eda68496892e0308f73e9577a)
- Created new CommentThread component which contains the thread head, replies, and wip comment (located below the existing replies)
- CommentThread component created by splitting up the ExistingComment component
2. View Great Gatsby translation
3. Reply to a comment
4. Observe that WIPComment appears below existing replies
- Is the code readable?
- Does the implementation make sense?
> Open WIP comment under bottom of thread on reply

- backend/python/app/graphql/types/story_type.py
- backend/python/app/services/implementations/story_service.py
- frontend/src/APIClients/queries/StoryQueries.ts
- frontend/src/components/admin/StoryTranslationsTable.tsx
- frontend/src/components/admin/TableFilter.tsx
- frontend/src/components/homepage/PreviewModal.tsx
- frontend/src/components/userProfile/AssignedStoryTranslationsTable.tsx
- frontend/src/utils/StageUtils.ts
https://www.notion.so/uwblueprintexecs/Show-translate-or-review-on-StoryTranslationTable-85a6a0739c3a459a88aae5dfdb4ccf78
- updated `get_story_translations` query to return num_translated_lines, num_approved_lines, and num_content_lines
- fetch + display progress in `StoryTranslationsTable.tsx` and `AssignedStoryTranslationsTable.tsx`
2. Observe that the progress % is shown for stories in translation + review
3. Go to any user's profile page
4. Verify that progress % is shown in the assigned story translations table
- does it appear correctly?
> Show progress percentage for story translations

- frontend/src/components/pages/UserProfilePage.tsx
[if user has no resume, hide resume on admin view of user profile][(https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d](https://www.notion.so/uwblueprintexecs/if-user-has-no-resume-hide-resume-on-admin-view-of-user-profile-63841962768b4fe3a96f4d71280d6149))
- Hide the resume and file section if resume is null 
1. Login as angela merkel
2. Navigate to any user without a resume 
3. Make sure resume does work for users with resume
-
> Hide resume when null

- frontend/src/APIClients/queries/StoryQueries.ts
- frontend/src/components/homepage/MyWorkFilter.tsx
- frontend/src/components/homepage/StoryCard.tsx
- frontend/src/components/pages/HomePage.tsx
https://www.notion.so/uwblueprintexecs/Add-My-Work-filter-1e54939fb0784090b9a7a94db0f5f1bd
- created `MyWorkFilter.tsx` component
- filter stories on homepage based on stage (My Work tab only)
1. Login as any user
2. Observe that filter appears on "My Work" tab
3. Play around with the filter and verify that the stories are displayed correctly
4. Switch tabs and verify that the stage filter is not applied on other tabs
> Add my work filter on homepage

- backend/python/app/graphql/queries/story_query.py
- backend/python/app/graphql/schema.py
- backend/python/app/services/implementations/story_service.py
- backend/python/app/services/interfaces/story_service.py
[Implement getLanguages query](https://www.notion.so/uwblueprintexecs/Implement-getLanguages-query-9609930e7a2c4b1490ccdce8c8dc694a)
- added query to get languages
1. Rebuild containers and make sure database is up to date
2. Run [this query](http://localhost:5000/graphql?variables=null&operationName=GetLanguages&query=query%20GetLanguages%20%7B%0A%20%20languages%0A%7D%0A)
3. Verify response looks like:
```
{
"data": {
"languages": [
"ARABIC",
"ASANTE TWI",
"ASSAMESE",
"BENGALI",
"BHILI",
"CATALAN",
"CHATINO",
"DANISH",
"DUTCH",
"ENGLISH_UK",
"ENGLISH_US",
"ENGLISH_INDIAN",
"ESPERANTO",
"FRENCH",
"GEORGIAN",
"GERMAN",
"GREEK",
"GUJARATI",
"HEBREW",
"HINDI",
"INDONESIAN",
"ITALIAN",
"JAPANESE",
"KANNADA",
"KAZAKH",
"KHMER",
"KOTAVA",
"KURDISH",
"KUTCHI",
"LIDEPLA",
"MALAYALAM",
"MALTESE", …
```
> Implement getLanguages query

- frontend/src/components/admin/StoryTranslationsTable.tsx
- frontend/src/components/pages/ManageStoryPage.tsx
- frontend/src/components/pages/ReviewPage.tsx
- frontend/src/components/userProfile/AssignedStoryTranslationsTable.tsx
https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=35a2478937d24f45b26f3a40c5539b24
- redirect if user not reviewer and user not admin
- linked to review page on story translation tables
1. login as angela 
2. click on a link on manage story translations. observe that you can view the translation on the review page
3. click on a link on manage story translations. then click a link in the story translations. observe that you can view the translation on the review page
4. click on a user's link. then click a link in the story translations. observe that you can view the translation on the review page
- happiness and fulfillment in life
> Fix: Allow admins to view disabled ReviewPage

- .gitignore
- backend/python/app/graphql/mutations/story_mutation.py
- backend/python/app/graphql/schema.py
- backend/python/app/services/implementations/story_service.py
- backend/python/app/services/interfaces/story_service.py
- frontend/src/APIClients/mutations/StoryMutations.ts
[Ticket ](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=bc4ee7a18fb04effbb86a4e9da0bd362)
- Create process story service that reads file and extracts story information without committing changes to the database
1. Place this file in your root directory 
[test_story_file.docx](https://github.com/uwblueprint/planet-read/files/7803441/test_story_file.docx)
2. [Log in as Angela Merkel on GQL](http://localhost:5000/graphql?query=%0Amutation%20%7B%0A%20%20login%20(email%3A%22planetread%2Bangelamerkel%40uwblueprint.org%22%2C%20password%3A%22%22)%20%7B%0A%20%20%20%20accessToken%0A%20%20%20%20refreshToken%0A%20%20%20%20id%0A%20%20%7D%0A%7D&operationName=undefined) and retrieve the auth_token, set the variable `auth_token`
3. Run `curl …
> Create Process Story Service

- backend/python/app/graphql/mutations/auth_mutation.py
- backend/python/app/graphql/schema.py
- frontend/src/APIClients/AuthAPIClient.ts
- frontend/src/APIClients/BaseGQLClient.ts
- frontend/src/APIClients/mutations/AuthMutations.ts
- frontend/src/components/auth/Logout.tsx
aight so theres two potential causes to issues people (eg @lynn-kim @Puepis @jennchenn ) were seeing yesterday night
1. refreshing tokens too often makes firebase upset
2. auth tokens might get cleared from local storage if a token is expired, but unless a page is refreshed or an error is thrown, the gql request will still go through and come back with errors
I was able to explicitly encounter 2, but not 1. heres what I did to try to fix things:
- tokens are never refreshed along side a request. ie, if you log in at 3:30, you'll be booted by 4:30 no matter what
- reload the window + throw an error if an expired token is encountered during a gql request
1. checkout main (NOT THIS BRANCH)
2. …
> Fix: clear + refresh window when tokens are expired

- backend/python/app/graphql/queries/language_query.py
- backend/python/app/graphql/schema.py
- backend/python/app/graphql/types/language_type.py
- backend/python/app/services/implementations/language_service.py
- backend/python/app/services/interfaces/language_service.py
[Ticket ](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=91c5a6a68efb4c48a3147c8173d38161)
- Add new `is_rtl` query for languages 
1. go to GQL and run [this](http://localhost:5000/graphql?query=query%20IsRtl%20%7B%0A%20%20isRtl(language%3A%20%22ARABIC%22)%20%7B%0A%20%20%20%20isRtl%0A%20%20%7D%0A%7D&operationName=IsRtl), ensure it returns `true`
2. Also test with another language like MANDARIN which should return `false`
- unifying quantum mechanics and general relativity
> add is_rtl query for languages

- backend/python/app/services/implementations/user_service.py
- frontend/src/APIClients/mutations/UserMutations.ts
- frontend/src/components/pages/UserProfilePage.tsx
- frontend/src/components/userProfile/UserProfileForm.tsx
- frontend/src/utils/Copy.ts
[Make user's profile page functional](https://www.notion.so/uwblueprintexecs/Make-user-s-profile-page-functional-fff5c71f952a4c7ea3b766fca52b3b7a)
- Implemented save changes and cancel buttons
1. Login as Carl (or another user)
2. Make changes to profile
3. Cancel changes
4. Changes should be gone
5. Make changes to profile (excluding email)
6. Save changes and confirm modal
7. Changes should be saved and page refreshed
8. Make changes to profile (including email)
9. Save changes  and confirm modal
10. Changes should be saved and user signed out (note that you will need to sign in with the new email)
11. Experiment with changing different fields, cancelling and saving in different orders, and closing the confirmation modal
- Does ui look ok? (e.g. modal message, _button placement_)
- Does …
> Make user's profile page functional

- frontend/src/components/pages/ImportStoryPage.tsx
https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=0555b5da6b0642b5aa9cfc4dc049a8cb
- added excludedLanguages state
- each select adds to excludedLanguages 
- badges display excludedLanguages 
- badges can be discarded and removed from excludedLanguages 
1. login as angela
2. go to http://localhost:3000/#/import-story
3. add some languages
4. remove some languages
5. try adding the same language again
6. play around
- does it work
> Multiselect excluded languages in Import Story

- frontend/src/components/onboarding/AssignTestGradeModal.tsx
- frontend/src/components/onboarding/TestFeedbackModal.tsx
- frontend/src/utils/Copy.ts
[Add tooltip to View Results modal](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=1c23d05559874283a1136897b05362be)
- Add tooltip to Assign Level, Assign ad Reviewer, and Feedback section on the results modal
1. Create and complete a test as a user 
2. Grade the test as admin and finalize the grade 
3. View results of test and ensure that the tooltip appears in three aforementioned areas 
- bending the moral arc of the universe towards justice
> Add tooltip to View Results modal

- frontend/src/components/translation/TranslationTable.tsx
- frontend/src/utils/Copy.ts
[Add “This test has been graded” tooptip to GradingPage](https://www.notion.so/uwblueprintexecs/Add-This-test-has-been-graded-tooptip-to-GradingPage-cd7e14d5375746d2bfb9d8d7dbf2f522)
- Show status column
- Added tool tip to status badges
2. Add and submit some tests
3. Login as Angela
4. Grade the tests
5. View the graded tests
6. Hover over status badges in status column, there should be a tool tip that says "This test has already been graded."
- Is code ok?
> Add “This test has been graded” tooptip to GradingPage

- frontend/src/APIClients/mutations/StoryMutations.ts
- frontend/src/components/pages/ImportStoryPage.tsx
- frontend/src/index.css
- frontend/src/theme/index.ts
[Make import story page functional](https://www.notion.so/uwblueprintexecs/Make-import-story-page-functional-1efdd94431684af68a257d71e98c9ed1)
- Added functionality to import story page
- Also slipped a very small change to use Noto for headings 
- Also some CSS linting made it into the PR, I just left it there but can remove it?
1. Log in as angela
2. Go to http://localhost:3000/#/story/15
3. Try uploading a story 
4. Check that it works! 
5. Check that you are redirected to the story page
> Make import story page functional

- backend/python/app/services/implementations/auth_service.py
- frontend/src/APIClients/BaseGQLClient.ts
https://www.notion.so/uwblueprintexecs/User-sign-up-is-broken-c012f711e5064df6bac19ed3e9176f2c
okay so there were a few issues with the signup flow:
1. on the frontend, the `refreshToken` field wasn't fetched
2. on the frontend, SignUp was triggering the `accessTokenFromInjectionLink`, which refreshes the page since there is no access token in local storage (took me wayyyy too long to find this)
3. on the backend, `dispatch_request` was calling the `create_user` function in user_service twice (which led to an `EMAIL_EXISTS` error, also took me way too long to resolve this)
1. Try signing up with a new email
2. Verify that you get logged and redirected to `/complete-profile`
3. Logout and try signing in again, verify that it works
- does signup work?
> Fixed signup

- frontend/src/APIClients/mutations/LanguageMutations.ts
- frontend/src/components/admin/AddLanguageModal.tsx
- frontend/src/components/admin/ManageStoryTranslations.tsx
- frontend/src/constants/Languages.ts
- frontend/src/utils/Copy.ts
https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=0bce90b6883443fdbc6ae18c0e945e63
- added AddLanguageModal
- converted the import story button on the manage story translation page to an add language button
1. login as angela
2. click the big phat language button
3. observe an intuitive and functional flow
4. confirm adding the language. do not refresh, immediately click the phat button again
5. observe the cleared modal. add another language just for fun
6. try messing around with modals as usual
- happiness, staying hydrated
- hows it look on different screen sizes?
> Implement admin add language modal

- frontend/src/components/pages/CompleteProfilePage.tsx
- frontend/src/components/pages/UserProfilePage.tsx
- frontend/src/components/userProfile/UserProfileForm.tsx
[Make left column sticky on UserProfile](https://www.notion.so/uwblueprintexecs/Make-left-column-sticky-on-UserProfile-a6c39451a61f40d88798a2010ba91b67)
- Changed styling to make navbar and sidebar stick
2. Go to profile
3. Resize window and scroll around
4. Navbar and sidebar should stick
5. Login as Angela
6. Go to some profiles
7. Resize window and scroll around
8. Navbar and sidebar should stick
- Does it look ok?
> Make left column sticky on UserProfile

- backend/python/app/graphql/mutations/story_mutation.py
- backend/python/app/services/implementations/story_service.py
- backend/python/app/services/interfaces/story_service.py
- backend/python/app/tests/services/test_story_service.py
- frontend/src/APIClients/mutations/StoryMutations.ts
- frontend/src/components/onboarding/AssignTestGradeModal.tsx
- frontend/src/components/pages/StoryTestGradingPage.tsx
- frontend/src/components/userProfile/ApprovedLanguagesTable.tsx
- frontend/src/components/userProfile/ApprovedLanguagesTableComponent.tsx
- frontend/src/components/userProfile/UserNewLanguageModal.tsx
- frontend/src/utils/Copy.ts
[Ticket Name](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=2a59105407934e1aae7d18fdf93ac775)
- Add option for user to check wants review when leveling up or adding a new language 
- Notify admin of user intention to be assigned language for review 
1. Level up a review language, this should create a new story test 
2. add new language, click the I want to be assigned as reviewer option 
3. Go to admin page, confirm that for both of these tests there is an alert indicating that the user would like to be assigned a language for review
- [ x] For backend changes, I have run the appropriate linters: `docker exec -it planet-read_py-backend_1 /bin/bash -c "black . && isort --profile black ."` and I have generated new migrations: …
> Allow user to start story test with intention to review

- frontend/src/components/auth/LoginComponent.tsx
- frontend/src/components/auth/LoginForm.tsx
- frontend/src/components/utils/InfoAlert.tsx
- frontend/src/utils/Copy.ts
[Alert user when signing up with a password shorter than 6 characters](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=c44b6c02042243bc92705ce42c54cf89)
- On signup page, alert user when their password is less than 6 characters
1. Go to sign up page, type in password shorter than 6 characters 
2. Confirm that the alert pops up
3. Type a password longer than 6 characters. Confirm that the alert disappears
> Alert user when signing up with a password shorter than 6 characters

- backend/python/app/services/implementations/story_service.py
- backend/python/app/services/implementations/user_service.py
- backend/python/app/tests/helpers/story_translation_helpers.py
- backend/python/app/tests/services/test_story_service.py
[Validate language params on backend](https://www.notion.so/uwblueprintexecs/Validate-language-params-on-backend-95459bb79283439f9f1d20e85947ab15)
- Validate any mutations where languages are added or updated (stories, users) 
Updated mutations:
- create_translation
- create_translation_test
- create_user
- update_user_by_id
1. Test each mutation with a fake language, and then with a real one - check that it fails and then succeeds
- Are there any other mutations that need validations?
> Validate language params on backend

- frontend/src/APIClients/queries/StoryQueries.ts
- frontend/src/components/auth/ResetPassword.tsx
- frontend/src/components/homepage/StoryCard.tsx
- frontend/src/components/pages/ImportStoryPage.tsx
- frontend/src/components/review/WIPComment.tsx
- frontend/src/components/translation/Autosave.tsx
[Ticket](https://www.notion.so/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=17ad2628b86d4452b659530ac032cb66)
-  Remove` console.log()` where appropriate 
1. If possible, try to recreate the errors and see if the window pops up
> Replace most console.logs with window.alerts

- frontend/src/components/userProfile/AdminNewLanguageModal.tsx
[Allow admin to approve translator language when user approved for reviewer](https://www.notion.so/uwblueprintexecs/Allow-admin-to-approve-translator-language-when-user-approved-for-reviewer-314504622d2e4a1bbb7231126c6b6a9d)
- added a hook to update language options when role is changed
1. Login as angela
2. Go to a reviewer
3. Add a new language that the user is not approved for, add as reviewer
4. Check that you can add the same language for translation, and check that other languages that they are already approved for do NOT show up
5. Try the other way around 
- Does it work
> Allow admin to approve translator language when user approved for reviewer

- frontend/src/components/auth/Login.tsx
- frontend/src/components/auth/LoginComponent.tsx
[Add loading indicator to login/signup page](https://www.notion.so/uwblueprintexecs/Add-loading-indicator-to-login-signup-page-8dddffb6a5e24badae26961ae1fff1ca)
- Set `isLoading` to true on sign in/register account button when request is made
- Reset `isLoading` to false after request is finished
2. Observe loading button and redirect as usual
3. Login as non-existent user
4. Observe loading button that switches back to normal button after error returns
5. Sign up with valid password
6. Observe loading button and redirect as usual
7. Sign up with invalid password (e.g. "a")
8. Observe loading button that switches back to normal button after error returns
- Does is work?
- Does it look ok?
> Add loading indicator to login/signup page

- frontend/src/APIClients/BaseGQLClient.ts
https://www.notion.so/uwblueprintexecs/Make-forget-password-work-716319eac5ca4a9a8a0b0a91b5087449
- currently on main branch, the reset password feature just refreshes the page. this is due to the basegqlclient throwing out the  request, like in #331 
- this is the last of all the auth mutations to not be considered in the basegqlclient
1. go to signup
2. input an email 
3. hit the forget password link
4. observe alert
5. check email, observe the reset password email from firebase
- happiness
- staying hydrated
- does it work
> Fix reset password refresh in BaseGQLClient

- frontend/src/components/pages/ReviewPage.tsx
[Hide comment panel if admin viewing story translation](https://www.notion.so/uwblueprintexecs/Hide-comment-panel-if-admin-viewing-story-translation-7e6ea619ce584f9a9419ef2b90cfa8ec)
- Added requirement that user is translator or reviewer to view comments
1. Login as Angela
2. View some translations where Angela is not a translator or reviewer
3. Observe no comments panel
4. View some translations where Angela is a translator (e.g. East of Eden German Level 4)
5. Observe comments panel
6. View some translations where Angela is a reviewer (use mysql `update story_translations set reviewer_id=6 where id=3` and look at War and Peace German Level 1)
7. Observe comments panel
> Hide comment panel if admin viewing story translation

- backend/python/app/graphql/mutations/file_mutation.py
- backend/python/app/graphql/mutations/language_mutation.py
- backend/python/app/graphql/mutations/story_mutation.py
- backend/python/app/graphql/mutations/user_mutation.py
- backend/python/app/graphql/queries/comment_query.py
- backend/python/app/graphql/queries/language_query.py
- backend/python/app/graphql/queries/story_query.py
- backend/python/app/tests/graphql/mutations/test_story_mutation.py
- backend/python/app/tests/graphql/queries/test_story_query.py
[Require user/admin role on most queries + mutations](https://www.notion.so/uwblueprintexecs/require-user-admin-role-on-most-queries-mutations-1518e6ffd2e441c1824fe79e063e8b00)
- Added user or admin role requirement to applicable queries and mutations
1. Use the platform to test if permissions are correct, or look at the code (I've commented some spots where I'm not sure about the authorization).
- Do the requirements look correct (please see comments especially)?
> Require user or admin role on most queries and mutations

- frontend/src/components/admin/StoriesTable.tsx
[Display story level in StoriesTable](https://www.notion.so/uwblueprintexecs/Display-story-level-in-StoriesTable-2ff36984c5b34ffd8d325fab6c699848)
- add level badge to manage stories table
2. Navigate to manage stories tab and verify level shows up
- did we want the level badges to show up?
> Display story level in StoriesTable

- frontend/src/components/pages/TranslationPage.tsx
- frontend/src/components/translation/Autosave.tsx
- frontend/src/utils/Copy.ts
[Prevent stage change until content changes are saved](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb)
- Add new state variable `changesSaved` to TranslationPage
- Button to submit story translation is disabled if this state is `false`
- State gets changed back to `true` once AutoSave calls `onSuccess()`
- Add tooltip message to warn user that their progress has not been saved 
1. Go to a storu translation
2. Change the story translation content
3. Observe that the button is disabled until the progress bar says 'Progress Saved'
4. Also see if the tooltip message appears when hovering over the button
- why is the world unjust
> Prevent stage change until content changes are saved

- frontend/src/components/admin/AddLanguageModal.tsx
[Notify admin that new language does not appear to be titlecase](https://www.notion.so/uwblueprintexecs/Notify-admin-that-new-language-does-not-appear-to-be-titlecase-fead049902df41518df8fdd8c82891f4)
- Display warning if language entered is not title case
- Currently messages stack for not titlecase and language already exists
1. Enter a language in the addlanguagemodal that isn't titlecase
2. Verify alert message is shown
- Whether regex is desired for determining titlecase
- Whether alerts should stack or language already exists message should be prioritized
> Notify user if entered language is not titlecase

- frontend/src/components/pages/ReviewPage.tsx
- frontend/src/utils/Copy.ts
[ Change “Submit Translation” to “Finish Translation” in ReviewPage #356 ](https://www.notion.so/uwblueprintexecs/Change-Submit-Translation-to-Finish-Translation-in-ReviewPage-d82196f7d33043d196f98ab4256fac5c)
- change `Submit Translation`->`Finish Translation`
1. Login as a reviewer who is currently reviewing a story
2. Navigate to the corresponding review page and approve all story lines
3. Verify button text now says `Finish Translation`, and relevant modal texts have been updated to say `Finish Translation` as well
[Jennifer_L15 assignment_grp 1.pdf](https://github.com/uwblueprint/planet-read/files/7923362/Jennifer_L15.assignment_grp.1.pdf)
- are all places where submit translation was used, changed?
> Change “Submit Translation” to “Finish Translation” in ReviewPage

- frontend/src/components/auth/LoginComponent.tsx
[Allow use of enter key on login/signup page](https://www.notion.so/uwblueprintexecs/Allow-use-of-enter-key-on-login-signup-page-3f42426584f348dc863d534cb5a742ac)
- Added enter key event listener
- Calls same function as login/signup button on click
- I enabled when button is (i.e. pressing enter does nothing when the corresponding button is disabled)
1. Go to login page
2. Enter login information
3. Press enter
4. Observe login
5. Go to signup page
6. Press enter
7. Observe that nothing happens when button is disabled
8. Enter signup information
9. Press enter
10. Observe signup
11. Please also test different combinations of entering information and pressing enter
- Does it work as expected?
- Is the code ok?
> Allow use of enter key on login/signup page

- frontend/src/components/homepage/StoryList.tsx
[Update the no stories copy on Homepage](https://www.notion.so/uwblueprintexecs/Update-the-no-stories-copy-on-Homepage-2697d4ad8a8248f198c9d1624754f992)
- change text that shows up when user is browsing stories and doesn't see any pop up
1. Login as Carl Sagan
2. Verify that the messages shown in `My Work`/`My Tests` tabs are unchanged
3. Click on `Browse Stories` and verify that new copy shows up (Carl Sagan should have active translations in both English US and UK)
- is the text changed for the correct scenario?
> Update the no stories copy on Homepage

- .circleci/config.yml
- bump node version in CircleCI to 14.17.0 (same as the Docker image version used locally) to avoid errors like [this](https://app.circleci.com/pipelines/github/uwblueprint/planet-read/2142/workflows/45701dd2-ce34-4f99-955c-5aa646807f06/jobs/3903)
I tested by running CircleCI w SSH, and manually bumping the node vers and running `yarn install`: 
- does the syntax look ok?
> Bump CircleCI Node Version to 14.17.0

- backend/python/Dockerfile
- backend/python/aml.ini
- backend/python/server.py
- backend/python/wsgi.py
THIS HAS NO CIRCLE CI CODE TO ACTUALLY DO ANY DEPLOYMENT STEPS
- rename `server.py` to `wsgi.py` (uwsgi expects `wsgi.py` as the entry point) 
- reuse `server.py` to invoke `create_app`. annoyingly uwsgi needs to see `application` imported in `wsgi.py` so we need to invoke `create_app` elsewhere 
- added `aml.ini` file for starting up the uwsgi server through systemctl (systemctl stuff doesnt need to be committed as its configured on machine. tho, it looks like this)
```
[Unit]
Description=uWSGI instance to serve planet-read
After=network.target
[Service]
User=bp-amluser
Group=www #this is nginx's user on the droplet
WorkingDirectory=/home/bp-amluser/planet-read/backend/python # will be modified
Environment="PATH=/home/bp-amluser/planet-read/planet-read/bin" # will be modified …
```
> Configure backend for uwsgi  deployment

- frontend/src/components/homepage/MyWorkFilter.tsx
- frontend/src/components/pages/HomePage.tsx
https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=248d523e745d4bdebfc6409293b60ad3
- accept isDefaultInReview param on MyStoriesFilter
- check if user is review and has story in review platform
1. reseed db
2. login as dwight and observe default IN TRANSLATION
3. move one of dwight's own stories to translation
4. observe default is still IN TRANSLATION
5. login as carl and move great gatsby to review (dwight is already reviewer)
6. login as dwight and observe default IN REVIEW
7. click between homepage tabs and observe behaviour
- does it work
- sleeping well
> Use "In Review" as default filter for reviewers with story translations in review

- frontend/src/components/admin/TableFilter.tsx
- frontend/src/utils/Copy.ts
[Do not disable dropdowns on TableFilter](https://www.notion.so/uwblueprintexecs/Do-not-disable-dropdowns-on-TableFilter-baa371befec9425895a8c86b3dcfd6dc)
- remove check to disable dropdown when value is set and corresponding tooltip
2. Play around with filters on `Manage Story Translations` tab
3. Verify that when an option is selected, dropdown no longer becomes disabled; when a new value is selected, it replaces the old value
4. Repeat for `Manage Stories`, `Manage Translators`, `Manage Reviewers`
- are there any other dropdowns that need to be modified?
> Do not disable dropdowns on TableFilter

- backend/python/app/services/implementations/story_service.py
- frontend/src/components/homepage/StoryCard.tsx
- frontend/src/components/homepage/StoryList.tsx
[Allow same user to be translator and reviewer on story translation](https://www.notion.so/uwblueprintexecs/Allow-same-user-to-be-translator-and-reviewer-on-story-translation-4b689c63d2ff4ef48159882114e71abc)
- remove check in backend preventing user from being assigned as reviewer if they are translator
- update frontend story card to reflect changes
1. Login as admin; upgrade Dwight D Eisenhower to be able to review Level 4 English (UK) translations
2. Login as Dwight; confirm Dwight is currently a translator on `Pride and Prejudice` English(UK)
3. Navigate to `Browse Stories`  tab, select Reviewer, English(UK), Level 4; click `Review` on `Pride and Prejudice`
4. Confirm that you were successfully assigned as reviewer
5. Navigate back to `My Stories` tab; confirm that `Pride and …
> Allow same user to be translator and reviewer on story translation

- backend/python/app/graphql/mutations/story_mutation.py
- backend/python/app/services/implementations/story_service.py
- backend/python/app/services/interfaces/story_service.py
- frontend/src/APIClients/mutations/StoryMutations.ts
- frontend/src/components/pages/ManageStoryPage.tsx
[Allow admin to update level on story](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=464f9a0b9b6d4d88a6a139dfedd5a67e)
- Add slider to Manage Story page to allow admin to update story level
- Update `UpdateStory` mutation to take in level parameter to update
1. Go to Manage Story page for a story
2. Update the level, click Save Changes 
3. Ensure no errors appear 
- Is it necessary to immediately update the badges in the Story Translations table as well?
> Allow admin to update level on story

- backend/python/app/graphql/mutations/story_mutation.py
- backend/python/app/middlewares/auth.py
- frontend/src/APIClients/mutations/StoryMutations.ts
- frontend/src/components/admin/StoryTestsTable.tsx
- frontend/src/components/admin/StoryTranslationsTable.tsx
- frontend/src/components/pages/ReviewPage.tsx
- frontend/src/components/pages/TranslationPage.tsx
- frontend/src/components/userProfile/AssignedStoryTranslationsTable.tsx
- frontend/src/utils/Copy.ts
[Allow users to quit story translations](https://www.notion.so/uwblueprintexecs/Allow-users-to-quit-story-translations-ea6058975b8040c796df52af571dd8d0)
- Added Remove myself from translation link to translation and review pages
- On translation page, call `SOFT_DELETE_STORY_TRANSLATION` to remove translator from translation
- On review page, call `UPDATE_STORY_TRANSLATION_STAGE` and `UNASSIGN_REVIEWER` to move story translation to in translation and remove reviewer from translation
- Added confirmation modals
- Modified authorization requirements on story mutations
- Modified `require_authorization_as_story_user_by_role` function in `auth.py` to work with `id` in `kwargs`
2. View To Kill a Mockingbird
3. Click Remove myself from translation link
4. Confirm modal
5. …
> Allow users to quit story translations

- backend/python/app/graphql/mutations/comment_mutation.py
- backend/python/app/services/implementations/comment_service.py
- frontend/src/components/pages/ReviewPage.tsx
- frontend/src/components/pages/TranslationPage.tsx
- frontend/src/components/review/CommentThread.tsx
- frontend/src/components/review/CommentsPanel.tsx
- frontend/src/components/review/WIPComment.tsx
https://www.notion.so/uwblueprintexecs/Allow-admins-to-comment-on-story-translations-efd4db5222ba4985a9aa71e7e08dd657
- modified `comment_service.py` to allow admins to create a comment
- modified `ReviewPage.tsx` to display comments panel
- made some changes to display "Admin" as the name if user is neither translator nor reviewer
1. login as admin
2. click on any story translation in the table
3. comment on any line, verify that name shows "Admin"
4. comment a reply
5. refresh to verify that name still shows "Admin"
6. sanity check: login as translator or reviewer and verify that commenting still works
- does the name show up correctly?
> Allow admins to comment on translations

- frontend/src/components/pages/ReviewPage.tsx
[Hide “remove myself from translation” if admin viewing platform](https://www.notion.so/uwblueprintexecs/Hide-remove-myself-from-translation-if-admin-viewing-platform-9070ed5859ea4b84b5750486c2162246)
- Hid “remove myself from translation” on review page if user is not the reviewer
1. Login as Angela Merkel
2. Go to a translation
3. Observe that “remove myself from translation” link is not there
> Hide 'remove myself from translation' if admin viewing platform

- frontend/src/components/auth/LoginForm.tsx
- frontend/src/components/auth/LoginImage.tsx
[Ticket](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=2e15fddc0d9e4db9a3f17025fd5e3871)
- Change margins of fields in signup page
1. Go to sign up page, see if the form is short enough
- :3
> Make sign up form shorter

- frontend/public/index.html
- frontend/src/components/navigation/Header.tsx
- frontend/src/components/pages/AdminPage.tsx
- frontend/src/components/pages/HomePage.tsx
- frontend/src/components/pages/ManageStoryPage.tsx
- fixes some tab links that were broken on prod->previously for tabs they would redirect the user to https://www.planetread.org/#/?tab=0 rather than https://www.planetread.org/aml_platform/#/?tab=0
1. Go to [the prod site](https://www.planetread.org/aml_platform)
2. Login as admin; click around on the tabs and verify that they redirect you as expected
3. Login as a regular user; click around on the tabs and verify that they redirect you as expected
- any other places to change?
> Fix broken tab links
