backend/python/app/models/__init__.py
backend/python/app/models/story.py

[Build stories model](https://www.notion.so/uwblueprintexecs/Build-Stories-model-d23a3d0a7a554d08b3d2737a481b39f6)
* add a model to app/models for Stories
* [database schema](https://www.notion.so/uwblueprintexecs/Build-Stories-model-d23a3d0a7a554d08b3d2737a481b39f6#50596b4cbf844d2c922ea678931074aa) 
* story col not added since we have yet to decide on a storage method 
1. tear down container with `docker-compose down --volumes` and rebuild with `docker-compose up --build`
2. go into `/backend/python/app/models/__init__.py` and change the `erase_db_and_sync = False` to `True`
3. `docker ps`
4. `docker exec -it <db-container-id> /bin/bash`
5. `psql -U postgres -d planet-read`
6. `\dt`
7. should have the following table with id and stage
8. you can try adding rows with `insert into stories …

Create story model

---

.circleci/config.yml

[Build docker image on pull request](https://www.notion.so/uwblueprintexecs/Build-docker-image-on-pull-request-c31abe83dbb64fd1a56c4e794d8587d6)
Decided to use CircleCI since other people on BP have experience with it and it was pretty well documented.
Before you test you need to join the BP project team on [CircleCI](https://circleci.com/) with your Github account.
1. Create a new branch.
2. Push the branch to Github, then go to the PlanetRead project.
3. Check your build, it should be successful (might take ~4 minutes)
4. Delete the docker-compose file (forcing an error).
5. Push the change to remote, now the build that just started should fail.
Not sure if the docker image installs the things we need. It's the basic one that CircleCI provides but might be worthwhile to check if we ever …

Set Up Build Testing on PR

---

backend/python/app/rest/auth_routes.py
frontend/src/APIClients/AuthAPIClient.ts
frontend/src/App.tsx
frontend/src/components/auth/Signup.tsx

[Enable users to sign up](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=4a47edc475b34bb99b25ff1fae2a5507&p=1bd14141728b455db746b839c04d6221)
* Created signup helper method
* Created flask endpoint
* Endpoint calls create_user method to create user in database and in firebase
* Created Signup page to facilitate user signup
1. Click the Sign Up button
2. Fill up Signup form
3. Press Sign up
4. Verify user was created on Firebase
5. Verify user was created in db
* Whether current implementation of flask endpoint follows standard
* If current implementation of signup form is desired

Enable users to sign up

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
backend/python/app/__init__.py
backend/python/app/graphql/__init__.py
backend/python/app/graphql/mutations/auth_mutation.py
backend/python/app/graphql/mutations/entity_mutation.py
backend/python/app/graphql/mutations/user_mutation.py
backend/python/app/graphql/queries/entity_query.py
backend/python/app/graphql/schema.py
backend/python/app/graphql/service.py
backend/python/app/graphql/types/entity_type.py
backend/python/app/graphql/types/user_type.py
backend/python/app/middlewares/auth.py
backend/python/app/models/__init__.py
backend/python/app/models/entity.py
backend/python/app/models/story.py
backend/python/app/models/user.py
backend/python/app/rest/__init__.py
backend/python/app/rest/auth_routes.py
backend/python/app/rest/entity_routes.py
backend/python/app/rest/file_routes.py
backend/python/app/rest/user_routes.py
backend/python/app/services/implementations/auth_service.py
backend/python/app/services/implementations/email_service.py
backend/python/app/services/implementations/entity_service.py
backend/python/app/services/implementations/file_service.py
backend/python/app/services/implementations/user_service.py
backend/python/app/utilities/firebase_rest_client.py
backend/python/requirements.txt
backend/python/server.py

n/a
* Added comand for backend linting to pr
template and read me
* linted everything. literally.
* README.md
* .git/PULL_REQUEST_TEMPLATE.md
* backend/requirements.txt

lint: use black and isort as backend standard

---

backend/python/app/graphql/mutations/auth_mutation.py
backend/python/app/graphql/schema.py
frontend/src/APIClients/AuthAPIClient.ts
frontend/src/components/auth/Signup.tsx

[Migrate Signup Endpoint to GraphQL](https://www.notion.so/uwblueprintexecs/Migrate-signup-endpoint-to-GraphQL-61fb1ad9f61f43a4b91457528f0138d2)
* Added SignUp class to auth_mutations.py
* Changed Signup.tsx 
* Changed AuthAPIClient.ts to use GraphQL instead of REST 
1. Go to Login Page 
2. Click 'Sign Up' 
3. Fill in fields for user sign up and click submit 
4. Verify that you are taken to the user dashboard 
5. Check that the new user you have created exists in Firebase 
* Verifying that the signup functionality works 
- [x ] My PR name is descriptive and in imperative tense
- [ x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ x] For backend changes, I have run the appropriate …

Create signup migration graphql

---

frontend/public/index.html
frontend/src/components/pages/Default.tsx
frontend/src/components/story/StoryCard.css
frontend/src/components/story/StoryCard.tsx
frontend/src/components/story/Tag.css
frontend/src/components/story/Tag.tsx
frontend/src/index.css

[Create story cards](https://www.notion.so/uwblueprintexecs/Create-Story-cards-e429754899ed457da1ddfe7ad2b01e81)
* Created `StoryCard` component that contains youtube video frame, two new `Tag` components, title, and description
* Passed in parameters via a sample data response (does not do the actual GraphQL call) 
* Added new component on Login screen for easy testing
* Added `Inter` font to match the designs
1. Run everything, default page should have this added at the bottom:
This is compared to the designs below. [Also, Figma.] (https://www.figma.com/file/hOYashRzmWan79lPqY38QT/Planet-Read?node-id=3222%3A1215) I've gotten a "good enough for now" from Russell
* ~Do we want to use scss or css? Am I styling correctly/missing some good practices around naming and etc?~
* ~Adjust the size …

Create StoryCard component

---

backend/python/app/graphql/__init__.py
backend/python/app/graphql/mutations/file_mutation.py
backend/python/app/graphql/queries/file_query.py
backend/python/app/graphql/schema.py
backend/python/app/graphql/types/file_type.py
backend/python/app/graphql/view.py
backend/python/requirements.txt

* created file by id resolver and create file mutation
```
curl http://localhost:5000/graphql   -F operations='{"query": "mutation ($file: Upload!) { createFile(file: $file) { ok }}", "variables":  "file": null }}'   -F map='{ "0": ["variables.file"]}'   -F 0=@hello.txt
```
```
{
fileById (id: 1){
path
}
}
```
Check that file exists

files: migrate file routes to graphql

---

frontend/src/App.tsx
frontend/src/components/pages/Default.tsx
frontend/src/components/pages/HomePage.tsx
frontend/src/components/story/StoryCard.css
frontend/src/components/story/StoryCard.tsx
frontend/src/components/story/StoryList.tsx

[Create a large table of story cards](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=4a47edc475b34bb99b25ff1fae2a5507&p=f2ebfec6aceb419492796d9fd1dceff7)
* Create /stories route and add button to access on default screen. Remove sample `StoryCard` that was there
* Create stories page with `StoryList` component and appropriate GraphQL query. This was based on the starter code entity query
* Fix up some CSS so it looks better
1. Start with empty stories database (or you can do this at the end if you prefer). Go to /stories endpoint either manually or via button on main page
2. Populate your stories database with data. There's no error handling if the youtube link isn't real so pls make it real
3. Login and go to the /stories endpoint. View stories; be happy.
I …

Create /stories endpoint with list of story cards

---

backend/python/app/graphql/mutations/story_mutation.py
backend/python/app/graphql/queries/story_query.py
backend/python/app/graphql/schema.py
backend/python/app/models/story_translation.py
backend/python/app/services/implementations/story_service.py
backend/python/app/services/interfaces/story_service.py

[Assign a User as reviewer to a StoryTranslation](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=4a47edc475b34bb99b25ff1fae2a5507&p=c881c4e871a24a7a886c013fa77e95c5)
* Created assign Reviewer mutation
* Created story translation by id method that returns a `StoryTranslationResponseDTO`
* Check's if story translation language is among the languages for the user, the language-level the user is approved for is greater or equal to the level of the story, the story translation is in the translate stage, and the story translation doesn't already have a reviewer
* If conditions pass, updates the story translation
1. Seed the database with 2 users ie. 
```
$ INSERT INTO users (first_name, last_name, auth_id, role, approved_languages) VALUES ('First', 'User', …
```

Create assign reviewer mutation

---

backend/python/app/graphql/queries/story_query.py
backend/python/app/graphql/schema.py
backend/python/app/services/implementations/story_service.py
backend/python/app/services/interfaces/story_service.py

[Add optional filter parameters to storyTranslationsByUser](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=4a47edc475b34bb99b25ff1fae2a5507&p=b534087b40944721a740417926fe851c) 
* in the resolver for storyTranslationsByUserID, added two parameters `language` and `level` that default to `None`
* Added these same two parameters to every other method that is called by the storyTranslationsByUserID resolver 
Steps to test are very similar to [PR #26](https://github.com/uwblueprint/planet-read/pull/26) 
1. Follow steps 1 and 2 for PR #26 to see the database with users, stories, and story translations 
2. Test out the query with 4 different sets of parameters: 
i. no  `language` and `level` 
ii. no  `language` but add a `level` that is greater than or equal to some of …

added optional parameters for storyTranslationsByUser

---

frontend/src/components/story/PrimaryButton.css
frontend/src/components/story/PrimaryButton.tsx
frontend/src/components/story/SecondaryButton.css
frontend/src/components/story/SecondaryButton.tsx
frontend/src/components/story/StoryCard.css
frontend/src/components/story/StoryCard.tsx
frontend/src/components/story/StoryList.tsx
frontend/src/components/story/Tag.css

[Add "translate/review book" button to story card](https://www.notion.so/uwblueprintexecs/Add-translate-review-book-button-to-story-card-4f3735126cdf46c9a36d0a900af6ca6c)
* Added translate/review button to story card
* Created primary/secondary button components
* Pressing button makes corresponding calls to createStoryTranslation / assignUserAsReviewer
* Note: currently hardcoding values that i need passed into StoryCard component in StoryList; these will need to actually be passed in at some point
1. Seed database with users and stories/story_translations; log into the frontend and navigate to `/stories`
```
$ INSERT INTO users (first_name, last_name, auth_id, role, approved_languages) VALUES ('First', 'User', <firebase_auth_id>, 'User', '{"HINDI":3}');
$ INSERT INTO users (first_name, …
```

Add translate/review story button to card

---

backend/python/app/graphql/types/story_type.py
backend/python/app/services/implementations/story_service.py

Some unblocking work for https://github.com/uwblueprint/planet-read/pull/39 and https://github.com/uwblueprint/planet-read/pull/40
- Query the `StoryTranslation` table, including the include_relationships trait for the conversion to dictionary so that it includes the `translation_content` field
- Do a session query on the `Story` table, joining with the `StoryTranslation` table to know which story to look at, and convert to a dictionary object
- Combine these two dictionary objects into one response dictionary
- Rename the `StoryTranslation` table's id attribute to `story_translation_id`
1. Try out all the queries and mutations around `StoryTranslationResponseDTO`. Check all the fields are there (my go-to is checking something on the Story table, StoryTranslation table, and …

Modify query to return story translation contents in response

---

backend/python/app/models/__init__.py
backend/python/app/models/comment.py

[Create Comment Model](https://www.notion.so/uwblueprintexecs/Create-Comment-Model-5efa299cc63f44e1b426a59df965468c)
* Creat new comment model in `backend/python/app/models/comment.py` 
* Add sqlalchemy relation to Comment model within `story_translation_contents` 
1. Rebuild docker containers and enter into 'psql' 
2. Ensure that the `comments` table is created and has the correct fields 
3. Insert into `comments` table and check for any errors 
* Ensure that the `comments` table is created and new objects can be added

Create Comment model

---

README.md

* This is technically ahead of its time (references change that will be made in https://github.com/uwblueprint/planet-read/pull/63) but well 🤭 
1. Not really, I just wanted to play with in-browser VScode
* Makes sense? Missing anything?

Update README.md for test and MySQL migration

---

backend/python/app/graphql/queries/comment_query.py
backend/python/app/graphql/schema.py
backend/python/app/services/implementations/comment_service.py
backend/python/app/services/interfaces/comment_service.py

* add get_comments_by_story_translation to comment service
* add resolve_comments_by_story_translation
1. run seed script
2. try [this query](http://localhost:5000/graphql?query=%7B%0A%20%20commentsByStoryTranslation(storyTranslationId%3A13)%7B%0A%20%20%20%20id%0A%20%20%20%20commentIndex%0A%20%20%20%20content%0A%20%20%20%20storyTranslationContentId%0A%20%20%7D%0A%7D) out 
* thoughts on the sqlalchemy query?

Create commentsByStoryTranslation query

---

backend/python/app/graphql/mutations/story_mutation.py
backend/python/app/graphql/schema.py
backend/python/app/middlewares/auth.py
backend/python/app/services/implementations/auth_service.py

[Add authorization checks for editing translations](https://www.notion.so/uwblueprintexecs/Add-authorization-checks-for-editing-translations-3d86e674e9984437ae4560d3eb6ae669)
* added wrappers for UpdateStoryTranslationContentById and UpdateStoryTranslationContents 
* added function to check if user is translator in `auth_service.py`
1. Try editing translations through front end while logged in (this should work)
2. Try editing through [graphiql](http://localhost:5000/graphql?variables=null&operationName=updateStoryTranslations&query=mutation%20updateStoryTranslations%20%7B%0A%20%20updateStoryTranslationContentById(storyTranslationContentData%3A%20%7BtranslationContent%3A%20%22hello%22%2C%20id%3A%201%7D)%20%7B%0A%20%20%20%20story%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20lineIndex%0A …

Add auth checks for editing translations

---

backend/python/app/graphql/queries/comment_query.py
backend/python/app/graphql/schema.py
backend/python/app/services/implementations/comment_service.py
frontend/src/APIClients/queries/StoryQueries.ts
frontend/src/components/review/CommentsPanel.tsx

[Create comment filter](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=4a47edc475b34bb99b25ff1fae2a5507&p=4bbbdf78aefc4b66a33e13bdd36ac8cb)
* add resolve query param to resolve_comments_by_story_translation
* i realized none of the params in our gql queries had required params. Updated that.
*  add super simple drop down to filter the comments displayed in the frontend 
1. try these three queries: [zero](http://localhost:5000/graphql?query=%7B%0A%20%20commentsByStoryTranslation(storyTranslationId%3A%2013)%7B%0A%20%20%20%20content%0A%20%20%7D%0A%7D), [one](http://localhost:5000/graphql?query=%7B%0A%20%20commentsByStoryTranslation(storyTranslationId%3A%2013%2C%20resolved%3A%20true)%7B%0A%20%20%20%20content%0A%20%20%7D%0A%7D), …

Add comment panel filter

---

frontend/src/theme/index.ts

* Fix customTheme declaration to allow Firebase deploy to succeed
1.
*

Fix customTheme declaration

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

- clarified effects of docker-compose down --volume in readme
- made backend lint command more copy-past friendly in pr template

Clarify README and make lint command more convenient

---

frontend/src/App.tsx
frontend/src/components/pages/AdminPage.tsx
frontend/src/components/pages/UserProfilePage.tsx

- added an admin page 
- added a user page with user id url param
1. log in 
2. visit http://localhost:3000/admin
3. http://localhost:3000/user/3
4. http://localhost:3000/user/4
5. etc
- does it work :D

Set up admin & user profile page

---

.circleci/config.yml
backend/python/Procfile

[run python linters in circle ci](https://www.notion.so/uwblueprintexecs/run-python-linters-in-circle-ci-4231b3383ff146fdbfd60af9673bd1a4)
- added linting step to CircleCI config (black and sort)
- (separate from this ticket but) added command to clear db and re-seed it on each Heroku deployment
- I have been manually clearing the table contents and re-seeding whenever there are changes to the seed data (e.g. when I enforced that each user could only translate/review 1 story per language)
1. Pull this branch and create a new branch 
2. Commit code that is improperly linted / with imports in an incorrect order
3. Create a draft PR and verify that that lint check fails
4. Fix all lint issues; push the changes and verify that the lint step of the CircleCI build is successful
* links to the …

Run python linters in CircleCI

---

frontend/src/components/auth/Login.tsx

[Fix alert [object Object] login bug](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=324709d7c0fb478d890378e9baa84a87)
- The google login component triggers it's onFailure function when third party cookies are blocked (ie, in incognito). The function is modified to not make an annoying window alert when used in incognito.
1. open the web app
2. clear your cookies and refresh
3. note no window alert
4. repeat 1-3 but in incognito
- your happiness 😎

Fix alert [object Object] login bug

---

backend/python/app/graphql/mutations/story_mutation.py
backend/python/app/graphql/schema.py
backend/python/app/services/implementations/story_service.py
backend/python/app/services/interfaces/story_service.py
backend/python/app/tests/graphql/mutations/test_story_mutation.py

[Implement update story mutation ](https://www.notion.so/uwblueprintexecs/Implement-update-story-mutation-27972df6d40b47b6a135bffb62965225)
- Implemented update story mutation
1. Use non-admin header in Altair (e.g. Dwight).
2. Run mutation:
`mutation {
updateStory (storyId: 6, title: "test title", description: "test description", youtubeLink: "test link",
) {
ok
}
}`
3. Should get error:
`{
"errors": [
{
"message": "You are not authorized to make this request.",
"locations": [
{
"line": 8,
"column": 5
}
],
"path": [
"updateStory"
]
}
],
"data": {
"updateStory": null
}
}`
4. Check table in mysql database using `select * from stories;` (should be unchanged).
5. Use admin header in Altair (e.g. Angela).
6. Run mutation:
`mutation {
updateStory (storyId: 6, title: "test title", description: …

Implement update story mutation

---

frontend/src/APIClients/BaseGQLClient.ts
frontend/src/APIClients/queries/StoryQueries.ts
frontend/src/components/admin/ManageStoryTranslations.tsx
frontend/src/components/admin/StoryTranslationsTable.tsx
frontend/src/components/utils/Paginator.tsx
frontend/src/index.tsx
frontend/src/utils/hooks/usePagination.tsx

[Paginate getStoryTranslations](https://www.notion.so/uwblueprintexecs/Paginate-getStoryTranslations-d86ce7ed0c904d469226b785af549c98)
- created a reusable hook to encapsulate logic for handling pagination results
- used the hook to paginate `storyTranslations`
- created UI component to control moving between pages
- removed duplicate apollo client in `index.tsx` 
1. Log into `planetread+angelamerkel@uwblueprint.org`
2. Go to `/admin`
3. Verify that the story translations table shows 10 items on the first page (and that it shows "1-10 of 13")
4. Click the "next page" button and verify that the remaining items are fetched and displayed properly
5. Apply the "German" language filter and verify that the correct items are displayed
6. Remove the filter and verify that the original results are …

Implement pagination for storyTranslations on frontend

---

frontend/src/utils/Utils.ts

Small fix for commenting bug

---

.circleci/config.yml
.git-ftp-include
README.md
backend/python/app/models/comment_all.py
backend/python/app/models/story_translation_all.py
backend/python/app/models/user_all.py
frontend/src/components/review/ExistingComment.tsx

[Modify CircleCI to push code to client server](https://www.notion.so/uwblueprintexecs/Modify-CircleCI-to-push-code-to-client-server-4a0f285dc95a483cb8970ca0e07c2b51)
- modify circleci config to push backend code+frontend build files to the FTP server
- added appropriate FTP server credentials to circleci
1. Verify that the release circleci deployment [succeeded](https://app.circleci.com/pipelines/github/uwblueprint/planet-read/1229/workflows/95bc206d-2598-4268-93fa-89a183cb3278/jobs/1820)
2. Check that the right files show up in the FTP server -> download the extension [here ](https://marketplace.visualstudio.com/items?itemName=Natizyskunk.sftp) and I'll send the config file!
- does it make sense to only deploy on `v.##` tags?
- what is a good name for the circleci workflow (if we …

Modify CircleCI to push code to client server pt1

---

frontend/src/App.tsx
frontend/src/components/admin/TableFilter.tsx
frontend/src/components/auth/Login.tsx
frontend/src/components/pages/CompleteProfilePage.tsx
frontend/src/components/utils/DropdownIndicator.tsx

[Add dummy complete profile page to signup flow](https://www.notion.so/uwblueprintexecs/Add-dummy-complete-profile-page-to-signup-flow-573b5be85f324994ac8e9bf4a8dccf65)
- Created dummy page
- Redirects to page on signup and redirects to homepage on clicking submit
1. Signup or visit the /complete-profile endpoint after logging in
2. Press the submit button and verify user is redirected to homepage
- Styling primarily

Create dummy complete profile form

---

backend/python/app/graphql/mutations/story_mutation.py
backend/python/app/graphql/schema.py
backend/python/app/services/implementations/story_service.py
backend/python/app/tests/services/test_story_service.py
backend/python/tools/insert_test_data.py

[Create a new StoryTranslationTest given a language and level](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=f2fc1d72f7ba4a9ca0c974c73e5b8891)
- added create_translation_test service
- added CreateStoryTranslationTest mutation
- added client provided story tests to insert script
- added unit test
3. [try this mutation](http://localhost:5000/graphql?query=mutation%20%7B%0A%20%20createStoryTranslationTest(userId%3A%201%2C%20level%3A2%2C%20language%3A%22FRENCH%22)%7B%0A%20%20%20%20story%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20translat …

Create new StoryTranslation test

---

backend/python/app/services/interfaces/story_service.py

- added documentaion
- look good???

Document create_translation and _translation_test

---

backend/python/app/services/implementations/story_service.py

[Update translated_languages in create_translation](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=eadd41971d79487681e9a2945467f3d7)
- Add to `create_translation` inside `story_service.py` to add new language to `story.translated_languages` column after creating a translation 
1. Assign new translation to user on admin page (can use GQL mutation directly as well) 
2. Check db to see that the story has a new entry in the `translated_languages` column
- Robustness, particularly, I am worried about a potential failure when we try to add a new entry to `translated_languages`
- If a failure happens, does the current `try   except` handle and roll back the db to the correct state?

Update translated_languages in create_translation

---

frontend/src/components/navigation/Header.tsx

[link “Add My Language” in nav bar to /](https://www.notion.so/uwblueprintexecs/link-Add-My-Language-in-nav-bar-to-625613db2d8d41f0a4cd215c048c4b7c)
- added link to "Add My Language"
1. Login as any user
2. Click on "Add My Language", 

Link "Add My Language" to homepage

---

backend/python/app/graphql/queries/story_query.py
backend/python/app/graphql/schema.py
backend/python/app/graphql/types/story_type.py
backend/python/app/services/implementations/story_service.py
frontend/src/APIClients/queries/StoryQueries.ts
frontend/src/components/admin/ManageStoryTranslations.tsx
frontend/src/components/admin/Statistic.tsx

[Implement admin story translations dashboard](https://www.notion.so/uwblueprintexecs/Implement-admin-story-translations-dashboard-00573e182002404799c38ce8d3baed83)
- Created `GET_STORY_TRANSLATION_STATISTICS` query to get number of story translations in translation, in review, and completed
- Created `Statistic` component to display statistics on manage story translations page
1. Login as Angela
2. Verify that the dashboard exists
3. Use mysql to check the `story_translations` table and verify the numbers displayed by the dashboard
4. Login as Carl
5. Send two story translations for review
6. Login as Dwight
7. Approve all lines on the Great Gatsby and publish it
8. Login as Angela
9. Use mysql to check the `story_translations` table and verify the numbers displayed by the dashboard
- Is …

Implement admin story translations dashboard

---

backend/python/app/services/implementations/story_service.py
frontend/src/components/pages/StoryTestGradingPage.tsx
frontend/src/components/review/StatusBadge.tsx
frontend/src/components/translation/TranslationTable.tsx
frontend/src/theme/colors.ts
frontend/src/theme/components/Badge.ts
frontend/src/utils/Copy.ts
frontend/src/utils/StatusUtils.ts
frontend/src/utils/Utils.ts

https://www.notion.so/uwblueprintexecs/Make-dummy-Test-Grading-platform-functional-4fdb0f5540e14c38acfed93e1d715013
- allow admin to update story line status to "PENDING" for tests
- redirect to 404 on `/grade` if not a story test
- wrap grading buttons in tooltips to handle story test in TRANSLATE stage
- implement modal for fail user flow (not functional yet)
- modified StatusBadge to accomodate test grading statuses
- keep track of score state in `StoryTestGradingPage.tsx`
3. run "UPDATE story_translations SET stage='REVIEW' WHERE id=13;" in the db container
4. create story test using mutation …

Make grading page functional

---

frontend/src/APIClients/queries/StoryQueries.ts
frontend/src/components/admin/ManageStories.tsx
frontend/src/components/admin/StoriesTable.tsx
frontend/src/components/navigation/Header.tsx
frontend/src/components/pages/AdminPage.tsx
frontend/src/utils/Copy.ts

https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=71c988ff431e43f4a1764d39c340b113
- modularize admin tabs generation on Header
- create ManageStories page
- create StoriesTable
- note: leaving filter for separate pr
1. login as good ol angela
2. navigate to Manage Stories
3. click on links
4. try to sort columns
5. hit delete button. observe the modal
6. confirmation doesnt actually do anything as the mutation isnt ready yet
- does it work
- does the code look lit

Set up Manage Story page & table

---

frontend/src/APIClients/queries/StoryQueries.ts
frontend/src/components/onboarding/AssignTestGradeModal.tsx
frontend/src/components/onboarding/Block.tsx
frontend/src/components/pages/StoryTestGradingPage.tsx
frontend/src/utils/Copy.ts

[Implement Assign Grade flow](https://www.notion.so/uwblueprintexecs/Implement-Assign-Grade-flow-58a5247b57134de6bd3da4086a2171ab)
- add assign grade modal
- make call to assign translate/review level after test is graded
1. [Create a test](http://localhost:5000/graphql?variables=null&operationName=CreateStoryTest&query=mutation%20CreateStoryTest%20%7B%0A%20%20createStoryTranslationTest(userId%3A%203%2C%20level%3A2%2C%20language%3A%22FRENCH%22)%7B%0A%20%20%20%20story%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20translatorId%0A%20%20%20%20%20%20storyId%0A%20%20%20%20%20%20language%0A%20%20%20%20%20%20stage%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)
2. Set test to review stage: `docker exec -it planet-read_db_1 mysql -u root -proot -e "UPDATE story_translations SET stage=2 WHERE is_test=1;"`
* …

Implement Assign Grade flow

---

backend/python/app/graphql/mutations/story_mutation.py
backend/python/app/graphql/schema.py
backend/python/app/services/implementations/file_service.py
backend/python/app/services/implementations/story_service.py
backend/python/requirements.txt

[Import Story from word document](https://www.notion.so/uwblueprintexecs/Import-Story-from-word-document-f7133f887e1c4f838269704ee133fed5)
- read files using python-docx
1. Rebuild docker !! 
2. Login and grab auth token 
3. Create a .docx file and add story content to it
4. Run this and check that the story and story content was populated correctly`curl http://localhost:5000/graphql -F operations='{"query": "mutation ($file: Upload!) { importStory(storyFile: $file, storyDetails:{title: \"StoryTitle\", description: \"testing the import story mutation\", youtubeLink:\"https://www.youtube.com/watch?v=MywN9_53AKI\", level: 1}) { story {id} }}","variables": {"file": null}}' -F map='{ "0": ["variables.file"]}' -F 0=@test_story_file.docx -H "Authorization: Bearer <Auth token>"`
5. Check that …

Import Story from word document

---

backend/python/app/tests/services/test_story_service.py

https://www.notion.so/uwblueprintexecs/Write-get_stories_available_for_translation-tests-in-test_story_service-py-46d1c4f9c8ce43f1b0af6791e7424c57
- create unit test for `get_stories_available_for_translation`
1. observe passing CI pipeline
- does the test code make sense?

create unit test for get_stories_available_for_translation

---

frontend/src/components/pages/UserProfilePage.tsx

[Take out date joined](https://www.notion.so/uwblueprintexecs/Take-out-date-joined-bef774c515904f729ee4b160a2fd700d)
- Removes date joined 
1. Go to http://localhost:3000/#/user/1 
2. Check that date joined section is gone 
- Does it work

Remove date joined

---

backend/python/app/tests/helpers/story_translation_helpers.py
backend/python/app/tests/services/test_story_service.py

https://www.notion.so/uwblueprintexecs/Write-assign_user_as_reviewer-update_story_translation_content-and-get_story_translations_availabl-49347a158176424baf13c1c47fc5b265
- fix unit test for `get_stories_available_for_translation`
- implement unit tests for `assign_user_as_reviewer`, `update_story_translation_contents`, `get_story_translations_available_for_review`
1. observe passing tests in the CI pipeline
-

Write various unit tests for story service

---

frontend/src/components/pages/UserProfilePage.tsx

https://www.notion.so/uwblueprintexecs/Redirect-to-ManageTranslators-on-user-deleting-aba82521a5654304a60ba55e492b8324
- redirect to `/?tab=2` instead of `/`
2. Go to any user page
3. Delete user, observe redirect to "Manage Translators" page

Redirect to Manage Translators page after deleting user

---

frontend/src/components/userProfile/ApprovedLanguagesTable.tsx

[Ticket ](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=11a9bd985c6b448aab822347a9a2df90)
- Change redirect location for `onConfirmationClick`
1. Go to user profile and create a test 
2. Ensure user is redirected to `My Tabs` page on homepage
- this is literally a 1 line change

Redirect to My Test tab on story test creation

---

frontend/src/components/pages/StoryTestGradingPage.tsx
frontend/src/components/review/StatusBadge.tsx
frontend/src/components/translation/TranslationTable.tsx

https://www.notion.so/uwblueprintexecs/Update-Review-progress-on-Grading-platform-a5c94f8e5f644f069dd617c23042f919
- calculate and fetch grading progress from `storyTranslationById` query
- display + update grading progress on frontend
- cleaned up some linting errors and unused code on `StoryTestGradingPage.tsx`
1. Start a story test on any user and submit for review
2. Login as admin, go to "Manage Tests" and click "Grade"
3. Update the content status badges, verify that the progress is updated correctly
4. Refresh the page, verify that the progress is the same
5. Sanity check: Login as `planetread+dwightdeisenhower@uwblueprint.org` and verify that the review page works as normal
- if you need to convert the story translation stage to REVIEW, use `UPDATE story_translations set …

Update Review progress on Grading platform

---

README.md

Update README with mysql cmd + test info

---

frontend/src/components/homepage/WelcomeModal.tsx
frontend/src/components/pages/CompleteProfilePage.tsx
frontend/src/components/pages/HomePage.tsx
frontend/src/utils/Copy.ts

https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=3714b8d75de041b683fa6ffc40bb4181
- new modal
1. login 
2. go to http://localhost:3000/#/?welcome=true
3. observe you can only close modal if you check box
4. go to http://localhost:3000/#/complete-profile
5. click submit button 
6. observe you are directed to go to http://localhost:3000/#/?welcome=true
- doth it work

Implement welcome modal

---

backend/python/app/graphql/view.py
frontend/src/APIClients/BaseGQLClient.ts

https://www.notion.so/uwblueprintexecs/Clear-cookies-if-tokens-expired-9bd1756cefca4d2fbcf99680fa2bdba8
- when i initially made the GQL client links, I made a false assumption that an expired token could be used to refresh a token. now the GQL client interrupts the request and clears cookies if the accesstoken is expired
- instead, we should refresh on every request to give the user an hour of more token usage. this is now reflected in the corrected ifstatement conditional in the gql client
- added better handling to the GQL view so that gql requests dont implode if they fail to refresh tokens
1. checkout main (NOT THIS BRANCH)
2. login in non-incognito.  keep the tab open
i. you can continue dev work in a different browser (eg firefox) or in incognito
3. come back to this ticket in an …

Fix: clear expired cookies

---

frontend/src/App.tsx
frontend/src/components/admin/ManageStories.tsx
frontend/src/components/admin/ManageStoryTranslations.tsx
frontend/src/components/pages/ImportStoryPage.tsx

[Set up dummy Import story page](https://www.notion.so/uwblueprintexecs/Set-up-dummy-Import-story-page-4924c290e75a40e096e89c64e29b5c5f)
- Added route for import story page
- Redirect users to import story page route upon clicking the import story button
- Created a dummy import story page
1. Login as Angela
2. Go to manage stories
3. Click on import story button
4. Verify that new page (http://localhost:3000/#/import-story) exists and matches Figma
- Does styling look ok?
- Is code readable?

Set up dummy Import story page

---

backend/python/app/services/implementations/story_service.py

https://www.notion.so/uwblueprintexecs/Mark-all-as-approved-sets-ALL-story-translation-contents-to-be-approved-23fc9d87bd4c41b3b11c1292c5565b87
- modifed `approve_all_story_translation_content` function to only update content lines associated with the story translation
1. reset db
2. `UPDATE story_translations SET stage='REVIEW' WHERE id=13;`
3. Login as `planetread+dwightdeisenhower@uwblueprint.org`
4. Review "The Great Gatsby" and click "Mark all as approved"
5. Go to db, use `SELECT * from story_translation_contents;`
6. Verify that only ids 41-50 have been modified to APPROVED, all others stay as DEFAULT (or whatever they were before)
- does it work lol

Fix: "Mark all as approved" behaviour

---

backend/python/app/services/implementations/story_service.py

[Add language, translator, reviewer names to exported story](https://www.notion.so/uwblueprintexecs/Add-language-translator-reviewer-names-to-exported-story-8358fc2df13041f2a6361200fcd938d5)
- Include extra details from the story translation to the doc
1. Login as angela merkel
2. Go to any completed story translation and download the file
3. Check that the correct information is included 
- Do we need to handle null cases?

Include story details in export

---

frontend/src/APIClients/mutations/UserMutations.ts
frontend/src/components/pages/CompleteProfilePage.tsx
frontend/src/components/pages/UserProfilePage.tsx
frontend/src/components/userProfile/UserProfileForm.tsx

[Start new story test in CompleteProfile](https://www.notion.so/uwblueprintexecs/Start-new-story-test-in-CompleteProfile-201d139f0ad4478199a186d89c98babd)
- Modify (and rename) frontend mutation to also call createStoryTest
1. Create a new user/navigate to `/complete-profile` endpoint for an existing user
2. Modify user details and submit
3. Verify a new story test has been created and user details have been changed
- mutation format

Start new story test in CompleteProfile

---

backend/python/app/graphql/mutations/language_mutation.py
backend/python/app/graphql/queries/language_query.py
backend/python/app/graphql/queries/story_query.py
backend/python/app/graphql/schema.py
backend/python/app/graphql/service.py
backend/python/app/graphql/types/language_type.py
backend/python/app/services/implementations/language_service.py
backend/python/app/services/implementations/story_service.py
backend/python/app/services/interfaces/language_service.py
backend/python/app/services/interfaces/story_service.py

[Implement addLanguage mutation](https://www.notion.so/uwblueprintexecs/Implement-addLanguage-mutation-cee0aca5b34f45d883e48ba79027ccd7)
- Separated language services from story service
- Added the addLanguage mutation
1. [Try the mutation, check that it works](http://localhost:5000/graphql?query=mutation%20%7B%0A%20%20addLangauge(language%3A%22fake%20language%22%2C%20isRtl%3A%20false)%7B%0A%20%20%20%20ok%0A%20%20%20%20language%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20language%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&operationName=undefined)
2. For sanity, check that the [getLanguage query](http://localhost:5000/graphql?query=query%20GetLanguages%20%7B%0A%20%20languages%0A%7D%0A&operationName=GetLanguages&variables=null) works as well 

Implement addLanguage mutation

---

backend/python/app/graphql/types/story_type.py
backend/python/app/services/implementations/story_service.py
frontend/src/APIClients/queries/StoryQueries.ts
frontend/src/components/onboarding/AssignTestGradeModal.tsx
frontend/src/components/onboarding/TestFeedbackModal.tsx
frontend/src/components/pages/StoryTestGradingPage.tsx
frontend/src/utils/Copy.ts

https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=99bca8b85d8b4c71a80aa583b3dd0c6b
- modified AssignTestGradeModal and TestFeedbackModal to toggle being disabled and display default values
- setting props as init state is an anti pattern, hence i didnt modify any defaults of state https://medium.com/@justintulk/react-anti-patterns-props-in-initial-state-28687846cc2e
- retrieve testfeedback and testresults in getstorytranslationbyid
1. log in as a user
2. go to profile. add new languages/level up thrice to generate two new story tests
3. go to homepage, and submit both story tests for review
4. login as angela
5. fail one story test. observe the fail flow still works
6. pass one story test with no reviewer level. observe the pass …

Allow admins to view story test results

---

frontend/Dockerfile
frontend/package.json
frontend/src/APIClients/BaseGQLClient.ts
frontend/src/APIClients/mutations/UserMutations.ts
frontend/src/components/pages/CompleteProfilePage.tsx
frontend/src/components/pages/UserProfilePage.tsx
frontend/src/components/userProfile/UserProfileForm.tsx

[Upload resume via CompleteUserProfile](https://www.notion.so/uwblueprintexecs/Upload-resume-via-CompleteUserProfile-50cf009fa2a54ad0bf47e64e0de7ffc5)
- Used `apollo-upload-client` to allow file upload (used `createUploadLink` instead of `createHttpLink` in the `ApolloClient` link)
- Had to change `node` version to work with `apollo-upload-client`
- Added both browse and drag and drop file upload
1. Login as Carl (or anyone else)
2. Go to `http://localhost:3000/#/complete-profile`
3. Click on browse files and upload a file (it should only allow you to upload a singe pdf or docx file)
4. Observe that the file appears below uploaded file
5. Drag and drop a file into the drop zone (it should only allow you to upload a singe pdf or docx file, please test multiple file types and multiple …

Upload resume via CompleteUserProfile

---

frontend/src/components/admin/StoryTestsTable.tsx

[Give View Test button white background](https://www.notion.so/uwblueprintexecs/Give-View-Test-button-white-background-fd3fdaa2c366403eba2898994f906220)
- Made `backgroundColor` white
2. Add and submit a story test
3. Login as Angela
4. Grade the story test
5. In manage tests tab, observe that the view test button has a white background
- Is the background white?

Give View Test button white background

---

frontend/src/components/auth/Login.tsx

- don't show alert if user closes the popup
1. Go to `/login`  and click sign up
2. Click "Sign Up with Google" and close the popup window
3. Verify that no alert appears

Don't show alert if user closes Google Signup Window

---

frontend/src/components/auth/LoginComponent.tsx
frontend/src/components/auth/LoginForm.tsx
frontend/src/components/utils/InfoAlert.tsx
frontend/src/utils/Copy.ts

[Ticket ](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=699ad8f517924bdfa425e5d07f88d08f)
- Require 8 character password, match with regex 
- Change alert message to reflect new requirements 
1. Go to sign up page 
2. Type valid password, ensure no alert 
3. Type invalid password, ensure alert appears
- Alert only appears on sign up page when user types password that does not meet the requirements

require 8 char password with one letter and one number

---

frontend/src/components/admin/ManageStoryTests.tsx
frontend/src/components/auth/LoginForm.tsx
frontend/src/components/homepage/WelcomeModal.tsx
frontend/src/components/pages/UserProfilePage.tsx

https://www.notion.so/uwblueprintexecs/Review-remove-frontend-TODOs-dbd468a4bcf345c0b9ecaad1fe30e92b
- addressed all TODOs
- display welcome modal for terms and conditions
- display resume
1. Go to login page and click on terms and conditions, verify that modal pops up
2. Login as a user and start a story test and upload resume
3. Sanity check: verify that changing name and stuff still works
3. Login as admin and verify that "Manage Tests" still fetches tests properly
4. Go to user's profile and verify that resume name is correct
- no more frontend TODOs!!

Cleaned up frontend TODOs

---

backend/python/app/graphql/mutations/story_mutation.py
backend/python/app/services/implementations/auth_service.py
backend/python/app/services/implementations/story_service.py
backend/python/app/services/implementations/user_service.py
backend/python/app/services/interfaces/story_service.py
backend/python/app/tests/helpers/story_helpers.py
backend/python/app/tests/services/test_story_service.py

[Review + remove backend TODOs](https://www.notion.so/uwblueprintexecs/Review-remove-backend-TODOs-50a1ec26ad334188b79f2b2ddeee230a)
- Addressed:
- fetch story translation in assign_user_as_reviewer
- translated_languages - changed to not null because of excluded languages 
- Removed:
- batch insert in create story - need to iterate over items anyways to map them 
- return lineIndex - not needed
- profile photo - not needed
- start a new story test - already addressed 
1. Check that the appropriate TODOs were addressed
2. Check the the updated services (assign_user_as_reviewer, pytest) still work as expected
-

Review + remove backend TODOs

---

frontend/src/APIClients/mutations/UserMutations.ts
frontend/src/components/pages/CompleteProfilePage.tsx

[Fix User Form Bad Request Error](https://www.notion.so/uwblueprintexecs/Fix-User-Form-Bad-Request-Error-db13316882884e42ab2fd4cdd65e5562)
- Added `wantsReviewer: false` argument to `COMPLETE_SIGN_UP` mutation call
1. Open network tab in developer tools
2. Sign up or sign in
3. Complete profile at `http://localhost:3000/#/complete-profile`
4. Send for review
5. Observe no network errors
- Does the code look ok?

Fix User Form Bad Request Error

---

.circleci/config.yml
frontend/yarn.lock

[Update code on Digital Ocean on release](https://www.notion.so/uwblueprintexecs/Update-code-on-Digital-Ocean-on-release-a67ea8c1c2d4461aa9f95bd80e108446)
- deploy backend folder to digital ocean droplet on versioned release
1. Check that file makes sense
2. SSH into droplet/connect to it via SFTP and check that a `/home/bp-amluser/aml/backend/.git-ftp.log` file exists  (and the whole app)
3. Here are links to the [initial init](https://app.circleci.com/pipelines/github/uwblueprint/planet-read/2093/workflows/5828d771-f99b-4d7c-b182-0b88857f1e42/jobs/3792) and [subsequent push](https://app.circleci.com/pipelines/github/uwblueprint/planet-read/2094/workflows/2e8add31-6f2c-403a-8d4a-e6219a7c2166/jobs/3793) builds
- ~~currently I'm writing the backend files to …

Update code on Digital Ocean on release

---

frontend/src/components/auth/LoginComponent.tsx
frontend/src/components/auth/LoginForm.tsx
frontend/src/utils/Copy.ts

[Validate email on LoginForm](https://www.notion.so/uwblueprintexecs/Validate-email-on-LoginForm-98d8225ad25240ba87970c7f7ecdebd4)
- add alert when user tries to sign up with invalid email
1. Navigate to sign up page
2. Enter various invalid combinations of invalid email addresses and verify alert appears
3. Enter a valid email address and verify alert goes away
- is there specific copy we wanted to use for the alert?

Validate email on LoginForm

---

frontend/src/components/review/WIPComment.tsx

[Leave comment option active](https://www.notion.so/uwblueprintexecs/Leave-comment-option-active-61fecc0620494f99bfb08a6ad7aec49f)
- Set comment line to 0 instead of -1 to keep comment buttons 
1. Login
2. View a translation
3. Leave a comment
4. Observe that comment buttons in the pending column remain

Leave comment option active

---

backend/python/Procfile

Update Procfile to use `wsgi.py`

---

frontend/src/components/admin/StoryTranslationsTable.tsx

[Sort by last edited on StoryTranslation table](https://www.notion.so/uwblueprintexecs/Sort-by-last-edited-on-StoryTranslation-table-c6d4c85937a54c959f0bab1d083b3caf)
- Used similar sort as other tables to sort by last edited
1. Add reviewer and translator activity dates to story translations
2. Login as angela
3. Check that clicking the table header sorts the rows by the last edited dates 

Sort by last edited on StoryTranslation table

---

backend/python/app/services/implementations/language_service.py
frontend/src/components/admin/AddLanguageModal.tsx

[Sort languages alphabetically in language modal](https://www.notion.so/uwblueprintexecs/Sort-languages-alphabetically-in-language-modal-c7773d85701d49d8a4b195c2d3101726)
- Just wrote basic sort function for the language options (Sorts only by alphabet, not case)
1. Login as admin and add a language on Manage Story Translations page
- Sort function implementation (should I use .toLowerCase() since that is used elsewhere or does it not matter?)

Sort languages alphabetically in language modal

---

backend/python/app/__init__.py
backend/python/app/services/implementations/auth_service.py
backend/python/app/services/implementations/comment_service.py
backend/python/app/services/implementations/file_service.py
backend/python/app/services/implementations/language_service.py
backend/python/app/services/implementations/story_service.py
backend/python/app/services/implementations/user_service.py
backend/python/app/services/implementations/utils.py

[MySQL Lost Connection](https://www.notion.so/uwblueprintexecs/MySQL-Lost-connection-c1e7ee9ff2744d68b4c3dc8735d0f9d1)
- add wrapper around all database calls to:
1. pre-ping database to ensure connection is open
2. catch any errors after commit and roll them back 
1. does the production database connection error out anymore?
- `backend/python/app/services/implementations/utils.py`
- is there a better way of ensuring connection is valid other than running `SELECT 1;` before each db query? it shouldn't be very expensive but not sure if it'd be preferable to retry once on error instead?

Debug MySQL Lost Connection Issues

---

backend/python/tools/seed_users.py

created script to import client's starter users. 
1. go to https://docs.google.com/spreadsheets/d/1g8qM-TSMqlS9BHI9gH7MKCNNpBRQCAfC/edit?usp=sharing&ouid=102752030803126082177&rtpof=true&sd=true
2. File > Download > tsv
3. Place the tsv in python>tools. The emails likely already have firebase users, so you'll need to scramble up the emails a bit.
4. `docker exec -it planet-read_py-backend_1 /bin/bash -c "python -m tools.seed_users"`
5. `docker exec -it planet-read_db_1 /bin/bash -c "mysql -u root -proot"`
6. observe users added to database 
- does it work
- as long as it works dont worry to much about code reusability lol

Create script to seed production users to database

---

backend/python/tools/insert_test_stories.py
backend/python/tools/seed_users.py

- in prod, the only seed data really needed are the test stories. sign up wont work without them. 
1. clear your db
2. docker exec -it planet-read_py-backend_1 /bin/bash -c "python -m tools.insert_test_stories"
3. observe le stories
4. try the full sign up flow (eg complete profile and trigger first story test)
- does it work

Create insert test stories script

---

frontend/src/components/auth/Login.tsx
frontend/src/components/auth/LoginComponent.tsx

N/A
- Removed Google sign up/sign in button
1. Go to http://localhost:3000/#/login
2. Observe no google sign in button
3. Click on sign up
4. Observe no google sign up button
5. Double check that normal sign in still works
- Has the Google sign up/sign in button been removed?
- Should I also remove backend code for Google auth?

Remove Google auth button
